"""The question bank: reusable questions that apply to any call. This module is
the source of truth for them. data/labelled_data/questions.jsonl is derived from it
(plus any question found only in labelled_data.jsonl, for forward compatibility).

Original questions in the generic shape of regulated-industry call QA. Four
families: vulnerability (two questions: is a characteristic present, tagged
with the FCA FG21/1 characteristic(s); and did the agent handle it), complaint
(a stated problem with a sought resolution), eod (expression of dissatisfaction,
broader than a complaint), and general_qa (call-observable conduct). For the
detection questions `fail` means "the thing was detected", matching how such
questions are scored in practice. Every question carries pass and fail;
partial_pass and NA are optional per question.

Run: uv run python -m src.synthesis.question_bank   (regenerates questions.jsonl)
"""

import json
import re
from pathlib import Path

from src.synthesis.schema import Question

OUT_DIR = Path(__file__).resolve().parents[2] / "data" / "labelled_data"


# Every question is written in the speaker vocabulary of the transcripts it is asked of
# (decision 2026-09-03): AppTek calls have `agent`/`customer`, Taskmaster conversations
# `assistant`/`user`, ACI-Bench visits `doctor`/`patient`, SPoRC episodes `host` plus
# diarisation tags. A question is shared across corpora only when its wording already
# applies verbatim (the role-agnostic `spk-` set, phrased in terms of "the speakers").
# `gen-` and the four family questions are AppTek's; `tm-` and `aci-` are their
# Taskmaster and ACI-Bench counterparts, dataset-specific by construction; `hst-` are
# SPoRC host-behaviour questions.
ALL = ["apptek", "taskmaster", "aci_bench", "sporc"]


def q(id, family, text, options, description="", tags=None, datasets=("apptek",)):
    return Question(
        id=id, source="bank", family=family, text=text, description=description,
        options=[{"value": v, "criteria": c} for v, c in options], tags=tags or [],
        dataset_allow_list=list(datasets),
    )


# Taskmaster's assistant/user conversations: the same conduct as the AppTek questions in the
# corpus's own vocabulary. Derived by substitution because the behaviours are identical; the
# derived text is what questions.jsonl records.
TM_WORDS = [(r"\bagent's\b", "assistant's"), (r"\bAgent's\b", "Assistant's"), (r"\bagent\b", "assistant"),
            (r"\bAgent\b", "Assistant"), (r"\bcustomer's\b", "user's"), (r"\bCustomer's\b", "User's"),
            (r"\bcustomer\b", "user"), (r"\bCustomer\b", "User"), (r"\bcall\b", "conversation")]


def _tm(text: str) -> str:
    for pat, rep in TM_WORDS:
        text = re.sub(pat, rep, text)
    return text


def tm_variant(base: Question) -> Question:
    """The Taskmaster counterpart of an AppTek question: id gen-NN-x -> tm-NN-x, vocabulary swapped."""
    return Question(
        id=re.sub(r"^(gen|vul|cmp|eod)-", lambda m: f"tm-{m.group(1)}-" if m.group(1) != "gen" else "tm-", base.id),
        source="bank", family=base.family, text=_tm(base.text), description=_tm(base.description),
        options=[{"value": o.value, "criteria": _tm(o.criteria)} for o in base.options], tags=base.tags,
        dataset_allow_list=["taskmaster"],
    )



# The FCA's published characteristics of vulnerability (FG21/1, Figure 1), used as the
# closed tag vocabulary for the vulnerability questions.
FCA_TAGS = ['physical disability', 'severe or long-term illness', 'hearing or visual impairment', 'mental health condition', 'addiction', 'low mental capacity or cognitive disability', 'retirement', 'bereavement', 'income shock', 'relationship breakdown', 'domestic abuse', 'caring responsibilities', 'other significant life circumstances', 'inadequate or erratic income', 'over-indebtedness', 'low savings', 'low emotional resilience', 'low knowledge or confidence in managing finances', 'poor literacy or numeracy', 'poor English language skills', 'poor or no digital skills', 'learning difficulties', 'no or low access to help or support']

VUL_DESC = "A characteristic of vulnerability is a personal circumstance that makes the customer especially susceptible to harm, particularly when a firm does not act with appropriate care. The FCA's guidance (FG21/1) groups them under four drivers: health (a condition or illness affecting the ability to carry out day-to-day tasks), life events (bereavement, job loss, relationship breakdown and similar), resilience (low ability to withstand financial or emotional shocks) and capability (low knowledge or confidence in managing finances, or low literacy, numeracy or digital skills). Vulnerability is about the customer's circumstances, not about a complaint or a bad outcome. Answer fail when such a characteristic is disclosed or clearly evident, and tag every characteristic present."


QUESTIONS: list[Question] = [
    q("vul-01-present", "vulnerability",
      "Does the customer show a characteristic of vulnerability during the call?",
      [("fail", "Clear indicators of vulnerability are present: the customer discloses or clearly displays a health condition, a significant life event, low financial resilience, or low capability to understand or manage the matter."),
       ("pass", "No indicator of vulnerability is present; the customer appears engaged, informed and capable throughout.")],
      description=VUL_DESC, tags=FCA_TAGS, datasets=["apptek"]),
    q("vul-02-handled", "vulnerability",
      "Where the customer showed a characteristic of vulnerability, did the agent recognise it and respond appropriately?",
      [("pass", "The agent acknowledges the vulnerability and responds to it: adapts tone, pace or explanation, offers extra time or a follow-up in writing, involves a trusted person, or signposts relevant support."),
       ("fail", "The agent does not appropriately address the vulnerability: continues with a standard script, ignores or brushes past the disclosure, or responds in a way that could add to the customer's difficulty."),
       ("NA", "The customer shows no characteristic of vulnerability.")],
      description=("Judge only the agent's handling of vulnerability the customer actually displayed. Evidence should be the agent's "
                   "responses to the customer's disclosure (or the points where a response was conspicuously missing), plus the "
                   "disclosure itself; general conduct elsewhere in the call is not relevant."),
      tags=FCA_TAGS, datasets=["apptek"]),
    q("cmp-01-complaint", "complaint",
      "Does the customer make a complaint during the call?",
      [("fail", "The customer makes a clear complaint and expects a resolution: they explicitly state a problem with the service, product or experience and ask for, or clearly expect, it to be put right."),
       ("pass", "No complaint is made. The customer may express mild frustration, but does not state a problem and seek a resolution.")],
      description=("A complaint is an expression of a problem, formal or informal, together with a request or expectation that it be "
                   "resolved. Frustration on its own is not a complaint; a complaint has a stated problem and a sought outcome."), datasets=["apptek"]),
    q("eod-01-dissatisfaction", "eod",
      "Does the customer express dissatisfaction during the call?",
      [("fail", "The customer clearly expresses unhappiness, frustration or dissatisfaction with the service, product, process or outcome."),
       ("pass", "The customer is satisfied or neutral throughout; no dissatisfaction is expressed.")],
      description=("An expression of dissatisfaction is any clear statement of unhappiness with how they have been treated, what they "
                   "received, how the process went or what the outcome was, whether or not they ask for anything to be done about "
                   "it. It is broader than a complaint: every complaint contains dissatisfaction, but dissatisfaction without a "
                   "sought resolution is not a complaint."), datasets=["apptek"]),
    q('gen-01-introduction', "general_qa",
      'Did the agent introduce themselves by name and state which organisation they represent?',
      [('pass', "Both the agent's name and the organisation are stated in the opening."),
       ('partial_pass', 'One of the two is stated but not both.'),
       ('fail', 'Neither is stated.')]),
    q('gen-02-account-holder', "general_qa",
      'Did the agent confirm they were speaking with the account holder or an authorised person before discussing the account?',
      [('pass', 'The agent confirms who they are speaking to before any account-specific information is shared.'),
       ('fail', 'Account-specific information is shared without confirming who is on the line.'),
       ('NA', 'No account or personal record is discussed.')]),
    q('gen-03-identity-verification', "general_qa",
      "Was the customer's identity verified before account details were discussed?",
      [('pass', 'At least two identifying details are requested and confirmed before any account-specific information is given.'),
       ('partial_pass', 'Only one identifying detail is checked, or verification happens after account details have already been discussed.'),
       ('fail', 'No identity verification takes place.'),
       ('NA', 'No account-specific information is discussed.')]),
    q('gen-04-address', "general_qa",
      "Was the customer's address confirmed during the call?",
      [('pass', 'The address, or its first line and postcode, is asked for and confirmed.'),
       ('fail', 'The address is never confirmed.'),
       ('NA', 'The call has no reason to confirm an address.')]),
    q('gen-05-contact-details', "general_qa",
      "Were the customer's contact details (phone number or email) confirmed or updated?",
      [('pass', 'A phone number or email address is confirmed or taken down.'),
       ('fail', 'Contact details are needed for a follow-up but never confirmed.'),
       ('NA', 'No follow-up contact is required.')]),
    q('gen-06-data-protection', "general_qa",
      "Did the agent explain, or obtain agreement to, how the customer's personal information would be used?",
      [('pass', 'The agent states how the information will be used or stored and the customer acknowledges it.'),
       ('fail', 'Personal information is collected without any explanation or acknowledgement.'),
       ('NA', 'No personal information beyond a name is collected.')]),
    q('gen-07-needs-established', "general_qa",
      "Did the agent establish the customer's specific needs before recommending anything?",
      [('pass', "The agent asks about the customer's situation and requirements and reflects them back before recommending."),
       ('partial_pass', 'Some needs are explored but the recommendation is made before they are confirmed.'),
       ('fail', 'A recommendation is made without exploring needs.'),
       ('NA', 'Nothing is recommended on the call.')]),
    q('gen-08-affordability', "general_qa",
      'Where a cost or ongoing payment was involved, did the agent check that the customer could afford it?',
      [('pass', "The agent asks about the customer's ability to pay before agreeing the cost."),
       ('fail', 'A cost is agreed without any affordability check.'),
       ('NA', 'No cost or payment is involved.')]),
    q('gen-09-open-questions', "general_qa",
      "Did the agent use open questions to understand the customer's situation, rather than only closed or leading questions?",
      [('pass', 'The agent asks open questions and lets the customer describe their situation.'),
       ('partial_pass', 'A mix, with leading questions steering some answers.'),
       ('fail', 'The agent relies on leading or closed questions throughout.')]),
    q('gen-10-costs-explained', "general_qa",
      'Were all costs, fees or charges the customer would incur stated clearly?',
      [('pass', 'Every applicable cost is stated with its amount or basis before the customer commits.'),
       ('partial_pass', 'Costs are mentioned but amounts or conditions are vague.'),
       ('fail', 'A cost the customer will incur is not mentioned.'),
       ('NA', 'No cost applies.')]),
    q('gen-11-risks-limitations', "general_qa",
      'Were the risks, limitations or downsides of the product or option discussed made clear?',
      [('pass', 'The agent states what the customer could lose, what is excluded, or what the option cannot do.'),
       ('partial_pass', 'Limitations are alluded to but not explained.'),
       ('fail', 'Only benefits are described.'),
       ('NA', 'No product or option is discussed.')]),
    q('gen-12-key-terms', "general_qa",
      'Were the key terms of what was agreed (what, how much, when, for how long) stated before the customer committed?',
      [('pass', 'All key terms are stated before commitment.'),
       ('partial_pass', 'Most terms are stated; at least one material term is omitted.'),
       ('fail', 'The customer commits without the key terms being stated.'),
       ('NA', 'The customer does not commit to anything.')]),
    q('gen-13-cancellation-rights', "general_qa",
      'Where the customer agreed to a product or service, was their right to cancel or cooling-off period explained?',
      [('pass', 'The cancellation right and its period are stated.'),
       ('fail', 'The customer agrees to something without being told how or whether they can cancel.'),
       ('NA', 'The customer does not agree to a product or service.')]),
    q('gen-14-alternatives', "general_qa",
      'Were alternative options presented, or the reason for recommending one option over others explained?',
      [('pass', 'At least one alternative is mentioned, or the choice is justified against alternatives.'),
       ('fail', 'A single option is presented as the only one with no justification.'),
       ('NA', 'No recommendation is made.')]),
    q('gen-15-timescales', "general_qa",
      'Where something was to happen after the call, was the customer given a specific timescale?',
      [('pass', 'A specific timescale (day, date or period) is given.'),
       ('partial_pass', "A vague timescale such as 'soon' or 'shortly' is given."),
       ('fail', 'No timescale is given.'),
       ('NA', 'Nothing is to happen after the call.')]),
    q('gen-16-read-back', "general_qa",
      'Were important details the customer provided read back to confirm they were captured correctly?',
      [('pass', 'Details such as numbers, spellings or dates are repeated back and confirmed.'),
       ('fail', 'Important details are taken down without confirmation.'),
       ('NA', 'No important details are provided.')]),
    q('gen-17-customer-actions', "general_qa",
      'Was the customer told what they themselves needed to do after the call (send documents, complete a form, make a payment, attend somewhere)?',
      [('pass', "The customer's own required actions are stated clearly."),
       ('partial_pass', 'An action is implied but not spelled out (what, how or by when is missing).'),
       ('fail', 'The customer has something to do but is not told.'),
       ('NA', 'Nothing is required of the customer after the call.')]),
    q('gen-18-empathy', "general_qa",
      'Where the customer expressed frustration, worry or disappointment, did the agent acknowledge it?',
      [('pass', "The agent acknowledges the customer's feeling before moving on."),
       ('fail', 'The feeling is ignored or dismissed.'),
       ('NA', 'The customer expresses no such feeling.')]),
    q('gen-19-name-use', "general_qa",
      "Did the agent use the customer's name at least once after the opening?",
      [('pass', 'The customer is addressed by name during the call, not only in the greeting.'),
       ('fail', "The customer's name is not used after the opening."),
       ('NA', "The customer's name is never established.")]),
    q('gen-20-questions-invited', "general_qa",
      'Was the customer given an opportunity to ask questions before the call ended?',
      [('pass', 'The agent explicitly asks whether the customer has any questions or needs anything else.'),
       ('fail', 'The call is closed without any such invitation.')]),
    q('gen-21-next-steps', "general_qa",
      'Were the next steps summarised before the call ended, including who does what and by when?',
      [('pass', 'What happens next, who is responsible and when are all stated.'),
       ('partial_pass', 'Next steps are mentioned without who or when.'),
       ('fail', 'No next steps are stated.'),
       ('NA', 'Nothing follows from the call.')]),
    q('gen-22-eligibility-explained', "general_qa",
      'Were the eligibility requirements or qualifying conditions for what the customer wanted explained?',
      [('pass', 'The conditions the customer must meet are stated before proceeding.'),
       ('partial_pass', 'Conditions are mentioned only in part or only when the customer asks.'),
       ('fail', 'The agent proceeds without stating conditions that apply.'),
       ('NA', 'Nothing discussed carries eligibility conditions.')]),
    q('gen-23-explicit-consent', "general_qa",
      "Did the agent obtain the customer's explicit agreement before actioning a change or purchase?",
      [('pass', 'The agent describes the change and the customer clearly agrees before it is actioned.'),
       ('fail', 'A change is actioned without clear agreement, or agreement is assumed.'),
       ('NA', 'No change or purchase is actioned.')]),
    q('gen-24-marketing-preferences', "general_qa",
      "Where the customer's details were being recorded for the first time, were their marketing or contact preferences asked?",
      [('pass', 'The agent asks how, or whether, the customer wishes to be contacted for marketing.'),
       ('fail', 'Details are recorded without asking preferences.'),
       ('NA', 'No new customer record is created.')]),
    q('gen-25-confirmation-to-follow', "general_qa",
      'Did the agent say that written confirmation would follow, and how?',
      [('pass', 'The agent states that confirmation will be sent and by what channel.'),
       ('fail', 'Something is agreed but no confirmation is offered.'),
       ('NA', 'Nothing requiring confirmation is agreed.')]),
    q('gen-26-full-name', "general_qa",
      "Did the agent establish the customer's full name?",
      [('pass', 'Both first name and surname are asked for or confirmed.'),
       ('partial_pass', 'Only a first name is established.'),
       ('fail', 'No name is established.')]),
    q('gen-27-reference-asked', "general_qa",
      "Did the agent ask for an account, booking, policy or order reference to locate the customer's record?",
      [('pass', 'A reference of that kind is requested and provided.'),
       ('fail', 'The agent proceeds without asking for one although the request concerns an existing record.'),
       ('NA', 'The request concerns no existing record.')]),
    q('gen-28-clarifying-question', "general_qa",
      "Where the customer's request was ambiguous or incomplete, did the agent ask a clarifying question before acting?",
      [('pass', 'The agent asks at least one clarifying question that narrows the request.'),
       ('fail', 'The agent acts on an assumption without clarifying.'),
       ('NA', 'The request is specific from the outset.')]),
    q('gen-29-preference-honoured', "general_qa",
      'Were the constraints the customer stated (dates, budget, location, dietary or similar) reflected in what the agent offered?',
      [('pass', 'Every stated constraint is respected in the offer.'),
       ('partial_pass', 'Some constraints are respected; at least one is ignored without acknowledgement.'),
       ('fail', "The offer disregards the customer's stated constraints."),
       ('NA', 'The customer states no constraints.')]),
    q('gen-30-availability-checked', "general_qa",
      'Did the agent check availability, eligibility or stock before confirming that something could be done?',
      [('pass', 'The agent checks (or says they are checking) before confirming.'),
       ('fail', 'The agent confirms without checking and is later corrected, or never checks.'),
       ('NA', 'Nothing is confirmed that would require a check.')]),
    q('gen-31-decline-explained', "general_qa",
      'Where the agent could not meet a request, did they explain why?',
      [('pass', 'A specific reason is given for what cannot be done.'),
       ('partial_pass', "A vague reason such as 'policy' with no detail."),
       ('fail', 'The request is declined with no reason.'),
       ('NA', 'Every request is met.')]),
    q('gen-32-total-amount', "general_qa",
      'Was the total amount the customer would pay stated before they agreed to it?',
      [('pass', 'A total figure is stated before agreement.'),
       ('partial_pass', 'Components are given but no total.'),
       ('fail', 'The customer agrees without any figure.'),
       ('NA', 'No payment is involved.')]),
    q('gen-33-payment-method', "general_qa",
      'Was the method or timing of payment confirmed with the customer?',
      [('pass', 'How and when payment is taken is stated and acknowledged.'),
       ('fail', 'Payment is arranged without confirming method or timing.'),
       ('NA', 'No payment is involved.')]),
    q('gen-34-date-time-quoted', "general_qa",
      'Where a delivery, appointment, arrival or completion was arranged, was a specific date or time quoted?',
      [('pass', 'A specific date and/or time is quoted.'),
       ('partial_pass', 'Only an approximate window is quoted.'),
       ('fail', 'No date or time is quoted.'),
       ('NA', 'Nothing is arranged for a future date.')]),
    q('gen-35-conditions-mentioned', "general_qa",
      'Did the agent proactively mention a relevant condition, restriction or exclusion that the customer had not asked about?',
      [('pass', 'At least one relevant condition is volunteered.'),
       ('fail', 'Conditions are only stated when the customer asks, or not at all.'),
       ('NA', 'No conditions apply to what is discussed.')]),
    q('gen-36-deadline-mentioned', "general_qa",
      'Where a deadline, expiry or time limit applied to the customer, was it stated?',
      [('pass', 'The deadline or time limit is stated with a date or period.'),
       ('partial_pass', 'A deadline is mentioned without saying when.'),
       ('fail', 'A deadline applies but is not mentioned.'),
       ('NA', 'No deadline or time limit applies.')]),
    q('gen-37-mistake-corrected', "general_qa",
      'Did the customer have to correct the agent about a detail during the call?',
      [('pass', "The customer corrects no detail; the agent's details are right first time."),
       ('partial_pass', 'The customer corrects one detail and the agent accepts it.'),
       ('fail', 'The customer corrects the agent more than once, or a correction is resisted.')]),
    q('gen-39-recap-of-agreement', "general_qa",
      'Did the agent recap what had been agreed (order, booking, change) before ending the call?',
      [('pass', 'The agent restates the agreed details and the customer confirms.'),
       ('partial_pass', 'A partial recap that omits at least one agreed detail.'),
       ('fail', 'No recap is given.'),
       ('NA', 'Nothing is agreed.')]),
    q('gen-40-further-help-offered', "general_qa",
      'Did the agent offer relevant additional help or options beyond the immediate request?',
      [('pass', 'A relevant further option or piece of help is offered.'),
       ('fail', 'Only the immediate request is handled.'),
       ('NA', 'The call ends before such an offer would be reasonable.')]),
    q('gen-41-contact-route', "general_qa",
      'Was the customer told how to get back in touch if they needed to (number, channel, hours or a named contact)?',
      [('pass', 'A specific way to make contact is given.'),
       ('fail', 'The customer is left without a route to follow up.'),
       ('NA', 'No follow-up could be needed.')]),
    q('gen-43-existing-customer-check', "general_qa",
      'Did the agent establish whether the customer already had a relationship with the organisation (an existing account, booking or policy)?',
      [('pass', 'The agent asks or confirms whether the customer is an existing customer.'),
       ('fail', 'The agent assumes one way or the other without asking.'),
       ('NA', 'The question is irrelevant to the request.')]),
    q('gen-44-personal-questions-explained', "general_qa",
      'When asking for personal or financial details, did the agent explain why they were needed?',
      [('pass', 'A reason is given for each request for personal or financial detail.'),
       ('partial_pass', 'A reason is given for some requests but not others.'),
       ('fail', 'Details are requested with no reason.'),
       ('NA', 'No personal or financial details are requested.')]),
    q('gen-45-option-comparison', "general_qa",
      'Where more than one option was presented, were the differences between them explained?',
      [('pass', 'The agent explains how the options differ on price, features or suitability.'),
       ('partial_pass', 'Options are listed with little or no comparison.'),
       ('fail', 'The customer is left to work out the differences.'),
       ('NA', 'Only one option is presented.')]),
    q('gen-46-email-or-number-readback', "general_qa",
      'Where an email address or phone number was provided, was it read back for confirmation?',
      [('pass', 'The email or number is repeated back and confirmed.'),
       ('fail', 'It is taken without being read back.'),
       ('NA', 'No email address or phone number is provided.')]),
    q('gen-47-expectation-set', "general_qa",
      "Did the agent set the customer's expectations about what would happen if the request could not be completed as planned?",
      [('pass', 'A contingency is explained (what happens if unavailable, delayed or declined).'),
       ('fail', 'No contingency is mentioned although the outcome is uncertain.'),
       ('NA', 'The outcome is certain on the call.')]),
    q('gen-48-customer-question-invited-mid', "general_qa",
      'Did the agent pause to invite questions during the explanation, not only at the end?',
      [('pass', 'The agent checks for questions at least once mid-explanation.'),
       ('fail', 'Questions are invited only at the end, or not at all.'),
       ('NA', 'No explanation long enough to warrant it is given.')]),
    q('gen-49-hold-or-wait-explained', "general_qa",
      'Where the customer had to wait while the agent looked something up, did the agent say what they were doing?',
      [('pass', "The agent narrates the wait ('bear with me while I check your booking')."),
       ('fail', 'There is silence or an unexplained pause.'),
       ('NA', 'No lookup or wait occurs.')]),
    q('gen-50-spelling-confirmed', "general_qa",
      'Where a name or address was given, was its spelling confirmed?',
      [('pass', 'The agent asks for or repeats the spelling of at least one name or address element.'),
       ('fail', 'Names or addresses are taken without confirming spelling.'),
       ('NA', 'No name or address is given.')]),
    q('spk-01-speakers-introduced', "general_qa",
      'Were the speakers introduced, by name or by who they are, at some point in the conversation?',
      [('pass', 'Every main speaker is introduced by name or by who they are.'),
       ('partial_pass', 'Some speakers are introduced, others never are.'),
       ('fail', 'No speaker is introduced.')], datasets=ALL),
    q('spk-03-speaking-time-shared', "general_qa",
      'Was speaking time shared reasonably between the speakers rather than one speaker monopolising it?',
      [('pass', 'Each main speaker contributes substantially.'),
       ('partial_pass', 'One speaker dominates but others still make sustained contributions.'),
       ('fail', 'One speaker delivers a near-monologue while others barely speak.')], datasets=ALL),
    q('spk-04-no-interrupting', "general_qa",
      'Did the speakers let each other finish speaking?',
      [('pass', 'Speakers are not cut off.'),
       ('partial_pass', 'Occasional interruptions that are acknowledged or yielded.'),
       ('fail', 'Speakers repeatedly talk over one another.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-05-clarifying-question', "general_qa",
      'When something said was unclear or ambiguous, did another speaker ask for clarification?',
      [('pass', 'A clarifying question is asked and answered.'),
       ('fail', 'Unclear statements pass without clarification.'),
       ('NA', 'Nothing said needed clarifying.')], datasets=ALL),
    q('spk-06-jargon-explained', "general_qa",
      'When technical terms, acronyms or specialist references were used, were they explained?',
      [('pass', 'Each specialist term is explained for a general listener.'),
       ('partial_pass', 'Some terms are explained, others assumed.'),
       ('fail', 'Specialist terms are used without explanation.'),
       ('NA', 'No specialist terms are used.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-07-claims-supported', "general_qa",
      'Were factual claims backed by a source, evidence, data or a concrete example?',
      [('pass', 'The main factual claims are supported.'),
       ('partial_pass', 'Some claims are supported, others asserted bare.'),
       ('fail', 'Claims are asserted without any support.'),
       ('NA', 'No factual claims are made.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-08-figures-specific', "general_qa",
      'When figures or quantities were given, were they specific rather than vague?',
      [('pass', 'Figures are given with actual numbers, dates or amounts.'),
       ('partial_pass', "A mix of specific and vague ('a lot', 'recently')."),
       ('fail', 'Only vague quantities are given.'),
       ('NA', 'No figures or quantities arise.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-10-disclosure-acknowledged', "general_qa",
      'When a speaker shared something personal or difficult, did another speaker acknowledge it?',
      [('pass', 'The disclosure is acknowledged before the conversation moves on.'),
       ('fail', 'The disclosure is passed over without acknowledgement.'),
       ('NA', 'No personal or difficult disclosure is made.')], datasets=["aci_bench", "sporc"]),
    q('spk-11-advice-given', "general_qa",
      'Did a speaker give advice or a recommendation directed at the listener?',
      [('fail', 'A speaker tells listeners what they should do, buy, avoid or try.'),
       ('pass', 'No advice or recommendation is directed at listeners.')], datasets=["apptek", "sporc"]),
    q('spk-12-advice-caveated', "general_qa",
      'Where financial, medical or legal advice was given, was a caveat or disclaimer stated?',
      [('pass', 'A caveat is stated (seek professional advice, individual circumstances vary, not advice).'),
       ('fail', 'Such advice is given with no caveat.'),
       ('NA', 'No financial, medical or legal advice is given.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-13-promotion-present', "general_qa",
      "Did the conversation include promotion of a product, service, sponsor or the speakers' own work?",
      [('fail', "A product, service, sponsor or the speakers' own offering is promoted."),
       ('pass', 'Nothing is promoted.')], datasets=["apptek", "sporc"]),
    q('spk-14-promotion-disclosed', "general_qa",
      'Where a product or service was promoted, was the commercial relationship (sponsorship, ownership, affiliation) made clear?',
      [('pass', 'The relationship is stated.'),
       ('fail', 'Promotion occurs with no disclosure of the relationship.'),
       ('NA', 'Nothing is promoted.')], datasets=["apptek", "sporc"]),
    q('spk-15-summary-at-end', "general_qa",
      'Was there a summary, conclusion or takeaway at the end of the conversation?',
      [('pass', 'A speaker wraps up with a summary or takeaway.'),
       ('partial_pass', 'A brief sign-off gestures at a conclusion without summarising.'),
       ('fail', 'The conversation ends without any wrap-up.')], datasets=ALL),
    q('spk-16-call-to-action', "general_qa",
      'Did a speaker ask listeners to do something (subscribe, visit, sign up, get in touch)?',
      [('fail', 'An explicit request to listeners is made.'),
       ('pass', 'No request is made of listeners.')], datasets=["apptek", "sporc"]),
    q('spk-17-questions-answered', "general_qa",
      'Were the questions one speaker put to another actually answered?',
      [('pass', 'Questions receive direct answers.'),
       ('partial_pass', 'Most are answered; some are deflected or left hanging.'),
       ('fail', 'Questions are largely evaded or ignored.'),
       ('NA', 'No speaker asks another a question.')], datasets=ALL),
    q('spk-18-topic-shifts-signposted', "general_qa",
      'Were changes of topic signposted rather than abrupt?',
      [('pass', 'Transitions are announced or bridged.'),
       ('partial_pass', 'Some transitions are signposted, others abrupt.'),
       ('fail', 'Topics change abruptly throughout.'),
       ('NA', 'The conversation stays on one topic.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-20-sensitive-topic-care', "general_qa",
      'Where a sensitive topic arose (illness, death, money troubles, abuse, addiction), was it handled with care?',
      [('pass', 'The topic is approached with sensitivity and without trivialising.'),
       ('fail', 'The topic is treated flippantly, judgementally or carelessly.'),
       ('NA', 'No sensitive topic arises.')], datasets=["aci_bench", "sporc"]),
    q('spk-21-listener-addressed', "general_qa",
      'Did a speaker address the listener directly at any point?',
      [('fail', "The audience is addressed directly ('you listening', 'if you are…')."),
       ('pass', 'The speakers only address each other.')], datasets=["sporc"]),
    q('spk-22-expertise-established', "general_qa",
      "Was the basis of a speaker's expertise or experience on the topic stated?",
      [('pass', "A speaker's relevant background or experience is stated."),
       ('partial_pass', 'Expertise is implied but never stated.'),
       ('fail', "No basis for any speaker's authority is given.")], datasets=["sporc"]),
    q('spk-23-offensive-language', "general_qa",
      'Did the conversation contain profanity or offensive language?',
      [('fail', 'Profanity or offensive language occurs.'),
       ('pass', 'None occurs.')], datasets=ALL),
    q('spk-24-claim-challenged', "general_qa",
      'When a surprising or contestable claim was made, did another speaker probe or challenge it?',
      [('pass', 'The claim is questioned or tested before being accepted.'),
       ('fail', 'Contestable claims pass unchallenged.'),
       ('NA', 'No contestable claim is made.')], datasets=["sporc"]),
    # ---- SPoRC, role-agnostic rare-event question (the customer-worded family questions do not apply to podcasts)
    q('spk-26-vulnerability-disclosed', "vulnerability",
      'Does any speaker disclose a characteristic of vulnerability about themselves?',
      [('fail', 'A speaker discloses, about themselves, a health condition, a significant life event, low financial resilience or low capability of the kinds described.'),
       ('pass', 'No speaker discloses such a characteristic about themselves; talking about other people or the topic in general does not count.')],
      description=VUL_DESC.replace("the customer", "the speaker").replace("customer's", "speaker's"), tags=FCA_TAGS, datasets=["sporc"]),
    # ---- ACI-Bench clinical visits (doctor / patient / patient_guest): the conduct the audit found meaningful there,
    # written for the clinic rather than substituted from the service-call wording
    q('aci-cmp-01-complaint', "complaint",
      'Does the patient make a complaint about their care or the service during the visit?',
      [('fail', 'The patient clearly states a problem with their care, treatment, the clinic or a previous encounter and asks for, or clearly expects, it to be put right.'),
       ('pass', 'No complaint is made. The patient may express frustration about symptoms or waiting, but does not state a problem with the care or service and seek a resolution.')],
      description=("A complaint is an expression of a problem with the care or service, together with a request or expectation that it be "
                   "resolved. Describing symptoms or discomfort is not a complaint."), datasets=["aci_bench"]),
    q('aci-eod-01-dissatisfaction', "eod",
      'Does the patient express dissatisfaction with their care, treatment or the service during the visit?',
      [('fail', 'The patient clearly expresses unhappiness or frustration with how they have been treated, a treatment that was given, the process or an outcome of care.'),
       ('pass', 'The patient is satisfied or neutral about their care; describing symptoms or worry about their health is not dissatisfaction with the care.')],
      description=("An expression of dissatisfaction is a clear statement of unhappiness with the care or service, whether or not the patient "
                   "asks for anything to be done. It is broader than a complaint."), datasets=["aci_bench"]),
    q('aci-03-identity-confirmed', "general_qa",
      "Was the patient's identity confirmed before their clinical details were discussed?",
      [('pass', 'The doctor confirms at least one identifying detail (full name, date of birth) before discussing records or results.'),
       ('partial_pass', 'Identity is confirmed only after clinical details have already been discussed.'),
       ('fail', 'No identity check takes place.'),
       ('NA', 'No records or results specific to the patient are discussed.')], datasets=["aci_bench"]),
    q('aci-11-risks-side-effects', "general_qa",
      'Were the risks, side effects or limitations of the treatment or option discussed made clear to the patient?',
      [('pass', 'The doctor states what could go wrong, what the side effects are, or what the treatment cannot do.'),
       ('partial_pass', 'Risks are alluded to but not explained.'),
       ('fail', 'Only the benefits of the treatment are described.'),
       ('NA', 'No treatment or option is discussed.')], datasets=["aci_bench"]),
    q('aci-12-plan-stated', "general_qa",
      'Were the key details of the plan (what will be done, when, for how long, and what follows) stated before the patient agreed to it?',
      [('pass', 'All key details of the plan are stated before the patient agrees.'),
       ('partial_pass', 'Most details are stated; at least one material element (dose, duration, follow-up) is missing.'),
       ('fail', 'The patient agrees to a plan whose details are not stated.'),
       ('NA', 'No plan is agreed.')], datasets=["aci_bench"]),
    q('aci-14-alternatives', "general_qa",
      'Were alternative treatments or options presented, or the reason for recommending one over others explained?',
      [('pass', 'At least one alternative is mentioned, or the choice is justified against alternatives.'),
       ('fail', 'A single course of action is presented as the only one with no justification.'),
       ('NA', 'No treatment or course of action is recommended.')], datasets=["aci_bench"]),
    q('aci-15-timescales', "general_qa",
      'Where something was to happen after the visit (results, referral, follow-up), was the patient given a specific timescale?',
      [('pass', 'A specific timescale (day, date or period) is given.'),
       ('partial_pass', "A vague timescale such as 'soon' or 'in a few weeks' is given."),
       ('fail', 'No timescale is given.'),
       ('NA', 'Nothing is to happen after the visit.')], datasets=["aci_bench"]),
    q('aci-16-history-read-back', "general_qa",
      'Were important details the patient provided (medications, doses, dates, symptom history) repeated back to confirm they were captured correctly?',
      [('pass', 'Details are repeated back and confirmed.'),
       ('fail', 'Important details are taken down without confirmation.'),
       ('NA', 'No such details are provided.')], datasets=["aci_bench"]),
    q('aci-18-empathy', "general_qa",
      'Where the patient expressed worry, frustration or distress, did the doctor acknowledge it?',
      [('pass', "The doctor acknowledges the patient's feeling before moving on."),
       ('fail', 'The feeling is ignored or dismissed.'),
       ('NA', 'The patient expresses no such feeling.')], datasets=["aci_bench"]),
    q('aci-19-name-use', "general_qa",
      "Did the doctor use the patient's name at least once after the opening?",
      [('pass', 'The patient is addressed by name during the visit, not only in the greeting.'),
       ('fail', "The patient's name is not used after the opening."),
       ('NA', "The patient's name is never established.")], datasets=["aci_bench"]),
    q('aci-20-questions-invited', "general_qa",
      'Was the patient given an opportunity to ask questions before the visit ended?',
      [('pass', 'The doctor explicitly asks whether the patient has any questions or concerns.'),
       ('fail', 'The visit is closed without any such invitation.')], datasets=["aci_bench"]),
    q('aci-21-next-steps', "general_qa",
      'Were the next steps summarised before the visit ended, including who does what and by when?',
      [('pass', 'What happens next, who is responsible and when are all stated.'),
       ('partial_pass', 'Next steps are mentioned without who or when.'),
       ('fail', 'No next steps are stated.'),
       ('NA', 'Nothing follows from the visit.')], datasets=["aci_bench"]),
    q('aci-23-consent', "general_qa",
      "Did the doctor obtain the patient's explicit agreement before ordering a test, starting or changing a medication, or making a referral?",
      [('pass', 'The doctor describes the test, medication or referral and the patient clearly agrees before it is arranged.'),
       ('fail', 'A test, medication or referral is arranged without clear agreement, or agreement is assumed.'),
       ('NA', 'No test, medication or referral is arranged.')], datasets=["aci_bench"]),
    q('aci-26-full-name', "general_qa",
      "Did the doctor establish or confirm the patient's full name?",
      [('pass', 'Both first name and surname are used or confirmed.'),
       ('partial_pass', 'Only a first name is used.'),
       ('fail', 'No name is used or confirmed.')], datasets=["aci_bench"]),
    q('aci-28-clarifying-question', "general_qa",
      "Where the patient's description of their problem was vague or incomplete, did the doctor ask clarifying questions before deciding?",
      [('pass', 'The doctor asks at least one clarifying question that narrows the problem.'),
       ('fail', 'The doctor proceeds on an assumption without clarifying.'),
       ('NA', "The patient's description is specific from the outset.")], datasets=["aci_bench"]),
    q('aci-34-appointment-quoted', "general_qa",
      'Where a follow-up, test or referral was arranged, was a specific date, time or interval quoted?',
      [('pass', 'A specific date, time or interval is quoted.'),
       ('partial_pass', 'Only an approximate window is quoted.'),
       ('fail', 'No date, time or interval is quoted.'),
       ('NA', 'Nothing is arranged for a future date.')], datasets=["aci_bench"]),
    q('aci-35-precautions-volunteered', "general_qa",
      'Did the doctor proactively mention a relevant precaution, restriction or warning sign that the patient had not asked about?',
      [('pass', 'At least one relevant precaution, restriction or warning sign is volunteered.'),
       ('fail', 'Precautions are only stated when the patient asks, or not at all.'),
       ('NA', 'No precautions apply to what is discussed.')], datasets=["aci_bench"]),
    q('aci-37-correction', "general_qa",
      'Did the patient have to correct the doctor about a detail of their history or situation during the visit?',
      [('pass', "The patient corrects no detail; the doctor's details are right first time."),
       ('partial_pass', 'The patient corrects one detail and the doctor accepts it.'),
       ('fail', 'The patient corrects the doctor more than once, or a correction is resisted.')], datasets=["aci_bench"]),
    q('aci-39-plan-recap', "general_qa",
      'Did the doctor recap the plan (diagnosis or working diagnosis, treatment, tests, follow-up) before ending the visit?',
      [('pass', 'The doctor restates the plan and the patient confirms.'),
       ('partial_pass', 'A partial recap that omits at least one element of the plan.'),
       ('fail', 'No recap is given.'),
       ('NA', 'No plan is made.')], datasets=["aci_bench"]),
    q('aci-40-further-help', "general_qa",
      "Did the doctor offer relevant additional help beyond the presenting problem (a screening, a referral, advice on a second concern)?",
      [('pass', 'A relevant further piece of help is offered.'),
       ('fail', 'Only the presenting problem is handled.'),
       ('NA', 'The visit ends before such an offer would be reasonable.')], datasets=["aci_bench"]),
    q('aci-41-contact-route', "general_qa",
      'Was the patient told how to get back in touch, or when to seek urgent care, if things changed?',
      [('pass', 'A specific route (number, portal, when to go to emergency care) is given.'),
       ('fail', 'The patient is left without a route to follow up.'),
       ('NA', 'No follow-up could be needed.')], datasets=["aci_bench"]),
    q('aci-44-sensitive-questions-explained', "general_qa",
      'When asking about sensitive matters (alcohol, drugs, sexual health, mental health, home situation), did the doctor explain why they were asking?',
      [('pass', 'A reason is given for each sensitive question.'),
       ('partial_pass', 'A reason is given for some sensitive questions but not others.'),
       ('fail', 'Sensitive questions are asked with no reason.'),
       ('NA', 'No sensitive questions are asked.')], datasets=["aci_bench"]),
    q('aci-45-option-comparison', "general_qa",
      'Where more than one treatment or option was presented, were the differences between them explained?',
      [('pass', 'The doctor explains how the options differ in effectiveness, side effects, burden or suitability.'),
       ('partial_pass', 'Options are listed with little or no comparison.'),
       ('fail', 'The patient is left to work out the differences.'),
       ('NA', 'Only one option is presented.')], datasets=["aci_bench"]),
    q('aci-47-contingency', "general_qa",
      "Did the doctor set the patient's expectations about what would happen if the treatment did not work or a result came back abnormal?",
      [('pass', 'A contingency is explained (what happens if no improvement, if a result is abnormal, if side effects occur).'),
       ('fail', 'No contingency is mentioned although the outcome is uncertain.'),
       ('NA', 'The outcome is certain at the visit.')], datasets=["aci_bench"]),
    q('aci-49-review-narrated', "general_qa",
      'Where the doctor paused to review records, results or images, did they say what they were doing?',
      [('pass', "The doctor narrates the pause ('let me have a look at your x-ray')."),
       ('fail', 'There is an unexplained pause or silence.'),
       ('NA', 'No such review occurs.')], datasets=["aci_bench"]),
    # ---- host behaviour (SPoRC only; the host is identified by identify_speakers.py and rendered `host:`)
    q('hst-01-sponsor-read', "general_qa",
      'Did the host read a sponsor message or advertisement during the episode?',
      [('fail', 'The host reads a sponsor message, advertisement or promotional code, however brief.'),
       ('pass', 'No sponsor message or advertisement is read by the host; mentions of products by other speakers do not count.')],
      description=("Only the host counts: this tests whether the host's turns can be told apart from everyone else's. A sponsor "
                   "message is an announcement on behalf of a third party (a company, product, service or offer), typically "
                   "with a name, offer or code, whether at the start, mid-episode or at the end."), datasets=["sporc"]),
    q('hst-02-host-named', "general_qa",
      'Did the host state their own name during the episode?',
      [('pass', 'The host says their own name (in an introduction, sign-off or aside).'),
       ('fail', 'The host never says their own name.')], datasets=["sporc"]),
    q('hst-03-guest-introduced', "general_qa",
      'Did the host introduce the guest(s) by name and say who they are or why they are on the show?',
      [('pass', 'Each guest is introduced by name with a description of who they are.'),
       ('partial_pass', 'A guest is named but not described, or described but not named.'),
       ('fail', 'A guest speaks without any introduction by the host.'),
       ('NA', 'There is no guest: the other speakers are co-hosts or the episode is a monologue with interjections.')],
      datasets=["sporc"]),
    q('hst-04-host-shares-floor', "general_qa",
      'Did the host give the other speakers room to answer, or dominate the conversation?',
      [('pass', 'The host asks and then listens; other speakers complete their answers.'),
       ('partial_pass', 'The host occasionally talks at length over what should be an answer, but others still get substantial turns.'),
       ('fail', "The host delivers long monologues, cuts answers short or answers their own questions.")], datasets=["sporc"]),
    q('hst-06-host-restates', "general_qa",
      "Did the host restate or summarise a point another speaker made, to check or highlight it?",
      [('pass', 'At least once the host paraphrases or summarises what another speaker said.'),
       ('fail', 'The host never restates or summarises anyone else\'s point.'),
       ('NA', 'No other speaker makes a substantive point.')], datasets=["sporc"]),
    q('hst-08-host-self-promotion', "general_qa",
      "Did the host promote their own products, memberships, social accounts or other shows?",
      [('fail', "The host promotes something of their own: a book, course, membership, newsletter, social account or another show."),
       ('pass', 'The host promotes nothing of their own; third-party sponsor messages do not count here.')], datasets=["sporc"]),
    q('hst-09-listener-messages', "general_qa",
      'Did the host read out or respond to listener messages, questions or reviews?',
      [('fail', 'The host reads or answers at least one message, question or review from a listener.'),
       ('pass', 'No listener messages, questions or reviews are read or answered.')], datasets=["sporc"]),
    # ================================================================ bank v3 additions (2026-09-04)
    # ---- AppTek service calls (agent / customer): conduct the first 48 do not cover, by theme
    # opening, recording, identity, data
    q('gen-54-personal-data-disclosed', "general_qa",
      "Did the agent disclose account or personal details before the customer's identity had been established?",
      [('fail', 'Account or personal details are read out before any identity check.'),
       ('pass', 'No account or personal details are disclosed before identity is established, or none are disclosed at all.')]),
    q('gen-55-date-of-birth', "general_qa",
      "Was the customer's date of birth requested as part of identification?",
      [('pass', 'The date of birth is asked for and given.'),
       ('fail', 'Identification is attempted without asking for the date of birth.'),
       ('NA', 'No identification is attempted on the call.')]),
    q('gen-56-security-question', "general_qa",
      'Did the agent ask a security question or for a password or memorable word before discussing the account?',
      [('pass', 'A security question, password or memorable word is requested and answered before account details are discussed.'),
       ('fail', 'Account details are discussed without any security question.'),
       ('NA', 'No account is discussed.')]),
    # needs, suitability, sales conduct
    q('gen-57-pressure-selling', "general_qa",
      'Did the agent apply pressure to make the customer decide on the call?',
      [('fail', "The agent uses urgency, repeated pushing or discouragement of taking time, to obtain a decision on the call."),
       ('pass', 'The customer is free to decide in their own time, or no decision is sought.')]),
    q('gen-58-upsell-relevant', "general_qa",
      "Where the agent offered an additional product or upgrade, was it relevant to what the customer had said they needed?",
      [('pass', 'The additional offer follows from a stated need or circumstance.'),
       ('fail', "The additional offer has no connection to anything the customer said."),
       ('NA', 'No additional product or upgrade is offered.')]),
    q('gen-59-suitability-questions', "general_qa",
      'Before recommending a product or plan, did the agent ask about the customer\'s usage, circumstances or goals?',
      [('pass', 'At least two questions about usage, circumstances or goals precede the recommendation.'),
       ('partial_pass', 'One such question precedes the recommendation.'),
       ('fail', 'The recommendation is made with no such questions.'),
       ('NA', 'No product or plan is recommended.')]),
    q('gen-60-customer-decline-respected', "general_qa",
      "When the customer declined an offer, did the agent accept the refusal without repeating the offer?",
      [('pass', 'The first refusal is accepted.'),
       ('partial_pass', 'The offer is repeated once, then the refusal is accepted.'),
       ('fail', 'The offer is repeated more than once after a refusal.'),
       ('NA', 'The customer declines nothing.')]),
    q('gen-61-misleading-claim', "general_qa",
      'Did the agent make a claim about a product, price or outcome that the call itself shows to be untrue or overstated?',
      [('fail', 'A claim is later contradicted on the call, or is stated as certain when it is not (a guarantee, "the best", "no risk").'),
       ('pass', 'No such claim is made.')]),
    # explanation and information
    q('gen-63-plain-language', "general_qa",
      'Did the agent explain terms or jargon in plain language when the customer showed they did not understand?',
      [('pass', 'Each term the customer queries or misunderstands is explained plainly.'),
       ('fail', 'The customer\'s confusion is met with the same term repeated or ignored.'),
       ('NA', 'The customer shows no sign of not understanding.')]),
    q('gen-64-understanding-checked', "general_qa",
      "Did the agent check the customer's understanding of an important explanation, rather than only asking whether they had questions?",
      [('pass', 'The agent asks the customer to confirm or restate what they understood, or asks a specific check question.'),
       ('fail', 'No check of understanding is made.'),
       ('NA', 'Nothing important enough to warrant a check is explained.')]),
    q('gen-65-interest-or-rate-stated', "general_qa",
      'Where a financial product was discussed, was the interest rate, APR or equivalent stated?',
      [('pass', 'The rate is stated with a figure.'),
       ('partial_pass', 'A rate is referred to but no figure is given.'),
       ('fail', 'A financial product is discussed with no mention of its rate.'),
       ('NA', 'No financial product is discussed.')]),
    q('gen-66-contract-length', "general_qa",
      'Where the customer agreed to a contract or plan, was its minimum term or length stated?',
      [('pass', 'The term or length is stated.'),
       ('fail', 'A contract or plan is agreed without its length being stated.'),
       ('NA', 'No contract or plan is agreed.')]),
    q('gen-68-exclusions-explained', "general_qa",
      'Where cover, a warranty or a guarantee was discussed, were its exclusions or limits mentioned?',
      [('pass', 'At least one exclusion or limit is stated.'),
       ('fail', 'Cover, warranty or guarantee is described with no exclusions or limits.'),
       ('NA', 'No cover, warranty or guarantee is discussed.')]),
    q('gen-69-documents-referenced', "general_qa",
      'Did the agent tell the customer where the full terms or documents could be found or that they would be sent?',
      [('pass', 'A location, link or dispatch of the full terms is mentioned.'),
       ('fail', 'Something with written terms is agreed and no reference to them is made.'),
       ('NA', 'Nothing with written terms is agreed.')]),
    q('gen-70-numbers-accurate', "general_qa",
      'Were the figures the agent quoted consistent throughout the call?',
      [('pass', 'Every figure quoted is consistent, or a correction is made and acknowledged.'),
       ('fail', 'A figure is quoted inconsistently without correction.'),
       ('NA', 'No figures are quoted.')]),
    # handling, process, holds, transfers
    q('gen-71-hold-permission', "general_qa",
      'Before placing the customer on hold, did the agent ask permission and say roughly how long?',
      [('pass', 'Permission is asked and a duration is given.'),
       ('partial_pass', 'Permission is asked or a duration given, not both.'),
       ('fail', 'The customer is put on hold without either.'),
       ('NA', 'The customer is not placed on hold.')]),
    q('gen-72-hold-return', "general_qa",
      'On returning from a hold, did the agent thank the customer for waiting or acknowledge the wait?',
      [('pass', 'The wait is acknowledged on return.'),
       ('fail', 'The agent resumes without acknowledging the wait.'),
       ('NA', 'There is no hold.')]),
    q('gen-75-callback-arranged', "general_qa",
      'Where the matter could not be resolved on the call, was a callback or follow-up arranged with a time?',
      [('pass', 'A callback or follow-up is arranged with a day, date or time window.'),
       ('partial_pass', 'A follow-up is promised without a time.'),
       ('fail', 'The matter is left unresolved with no follow-up.'),
       ('NA', 'The matter is resolved on the call.')]),
    q('gen-76-ownership', "general_qa",
      'Did the agent take ownership of the problem rather than deflecting it to another team or the customer?',
      [('pass', 'The agent commits to an action themselves or explains exactly what will happen next.'),
       ('fail', 'The agent blames another team, the system or the customer and commits to nothing.'),
       ('NA', 'No problem needs resolving.')]),
    q('gen-77-first-contact-resolution', "general_qa",
      "Was the customer's request fully dealt with by the end of the call?",
      [('pass', 'Everything the customer asked for is done or definitively answered.'),
       ('partial_pass', 'Part of the request is dealt with; the rest is deferred.'),
       ('fail', 'The request is not dealt with and no path to resolution is given.')]),
    q('gen-78-notes-taken', "general_qa",
      'Did the agent say they were noting or recording what the customer told them on the account?',
      [('pass', 'The agent says the information is being noted or updated.'),
       ('fail', 'Information that would need recording is given and nothing is said about recording it.'),
       ('NA', 'Nothing that would need recording is given.')]),
    # manner and soft skills
    q('gen-80-interrupting-customer', "general_qa",
      'Did the agent interrupt the customer while they were explaining something?',
      [('fail', 'The agent cuts across the customer more than once, or once at a material moment.'),
       ('pass', 'The customer is allowed to finish.')]),
    q('gen-81-tone-professional', "general_qa",
      'Did the agent remain courteous and professional throughout, including when the customer was difficult?',
      [('pass', 'The agent is courteous throughout.'),
       ('partial_pass', 'A lapse in tone occurs but is recovered.'),
       ('fail', 'The agent is curt, sarcastic or dismissive.')]),
    q('gen-82-active-listening', "general_qa",
      "Did the agent show they had heard the customer by reflecting or summarising what the customer said before responding?",
      [('pass', 'At least once the agent reflects or summarises the customer\'s point before responding.'),
       ('fail', 'The agent responds without ever reflecting what was said.')]),
    q('gen-84-blame-avoided', "general_qa",
      'Where something had gone wrong, did the agent avoid blaming the customer?',
      [('pass', 'The problem is discussed without attributing fault to the customer, or fault is attributed factually and without reproach.'),
       ('fail', 'The agent blames the customer in a reproachful way.'),
       ('NA', 'Nothing has gone wrong.')]),
    q('gen-85-filler-words', "general_qa",
      "Did the agent's speech contain frequent fillers or hesitations (um, uh, like, you know) that made explanations hard to follow?",
      [('fail', 'Fillers or hesitations are frequent enough to obscure an explanation.'),
       ('partial_pass', 'Fillers are noticeable but explanations remain clear.'),
       ('pass', 'Fillers are rare.')]),
    # closing and outcomes
    q('gen-86-outcome-stated', "general_qa",
      'Before the call ended, did the agent state the outcome of the call in one clear sentence?',
      [('pass', 'A clear outcome statement is given (what was done, decided or will happen).'),
       ('fail', 'The call ends without a clear outcome statement.')]),
    q('gen-87-reference-given', "general_qa",
      'Where a request, complaint or order was logged, was the customer given a reference number?',
      [('pass', 'A reference number is given.'),
       ('fail', 'Something is logged and no reference is given.'),
       ('NA', 'Nothing is logged.')]),
    q('gen-90-promise-kept-in-call', "general_qa",
      'Did the agent do everything they said they would do during the call (check something, read something back, send something)?',
      [('pass', 'Every in-call promise is fulfilled on the call.'),
       ('fail', 'The agent promises to do something on the call and does not.'),
       ('NA', 'No in-call promise is made.')]),
    # complaint handling (rare-event family, Sonnet): conditional on a complaint or dissatisfaction being raised
    q('cmp-02-acknowledged', "complaint",
      'Where the customer complained or expressed dissatisfaction, did the agent acknowledge it explicitly?',
      [('pass', 'The agent acknowledges the complaint or dissatisfaction in words before moving to resolution.'),
       ('fail', 'The complaint or dissatisfaction is passed over without acknowledgement.'),
       ('NA', 'No complaint or dissatisfaction is raised.')]),
    q('cmp-03-apology', "complaint",
      'Where the customer complained, did the agent apologise?',
      [('pass', 'An apology is given.'),
       ('fail', 'No apology is given.'),
       ('NA', 'No complaint is raised.')]),
    q('cmp-04-escalation-offered', "complaint",
      'Where the customer complained and the agent could not resolve it, was a formal complaint route or escalation offered?',
      [('pass', 'The agent offers to log a formal complaint, escalate, or explains how to escalate.'),
       ('fail', 'The complaint is unresolved and no route is offered.'),
       ('NA', 'No complaint is raised, or it is resolved on the call.')]),
    q('cmp-05-resolution-timescale', "complaint",
      'Where a complaint was logged, was the customer told when they would hear back?',
      [('pass', 'A timescale for a response is given.'),
       ('fail', 'A complaint is logged with no timescale.'),
       ('NA', 'No complaint is logged.')]),
    q('eod-02-dissatisfaction-cause', "eod",
      'Where the customer expressed dissatisfaction, did the agent ask what had gone wrong before responding?',
      [('pass', 'The agent asks about the cause, or the customer volunteers it and the agent engages with it.'),
       ('fail', 'The agent responds without establishing what the dissatisfaction is about.'),
       ('NA', 'No dissatisfaction is expressed.')]),
    q('vul-03-support-offered', "vulnerability",
      'Where the customer disclosed a difficult circumstance, did the agent offer or mention any support, adjustment or further help?',
      [('pass', 'The agent offers an adjustment, extra time, a specialist team, written follow-up or similar.'),
       ('fail', 'A difficult circumstance is disclosed and no support of any kind is offered.'),
       ('NA', 'No difficult circumstance is disclosed.')],
      description="A difficult circumstance is anything under the FCA's four drivers of vulnerability: health, a life event, low resilience or low capability. Judge only whether support was offered, not whether the customer accepted it.", tags=FCA_TAGS),
    # ---- AppTek, domain-specific conduct across its service domains (banking, insurance, telecoms, energy, travel, retail, delivery)
    q('gen-94-fee-explained', "general_qa",
      'Where a fee or charge was applied, disputed or waived, was the reason for it explained?',
      [('pass', 'The reason for the fee, or for waiving it, is explained.'),
       ('fail', 'A fee is applied, disputed or waived with no explanation.'),
       ('NA', 'No fee or charge arises.')]),
    q('gen-95-first-payment-details', "general_qa",
      'Where a payment arrangement or direct debit was set up, were the date and amount of the first payment stated?',
      [('pass', 'Both the date and the amount of the first payment are stated.'),
       ('partial_pass', 'One of the two is stated.'),
       ('fail', 'A payment arrangement is set up with neither stated.'),
       ('NA', 'No payment arrangement is set up.')]),
    q('gen-97-visit-window', "general_qa",
      'Where an engineer, delivery or collection visit was arranged, were the time window and any access requirement stated?',
      [('pass', 'A time window is given and access requirements (someone present, parking, keys) are mentioned.'),
       ('partial_pass', 'A time window is given but nothing about access.'),
       ('fail', 'A visit is arranged with no time window.'),
       ('NA', 'No visit is arranged.')]),
    q('gen-100-excess-stated', "general_qa",
      'Where an insurance policy or claim was discussed, was the excess stated?',
      [('pass', 'The excess amount is stated.'),
       ('fail', 'A policy or claim is discussed with no mention of the excess.'),
       ('NA', 'No insurance policy or claim is discussed.')]),
    q('gen-102-order-confirmed', "general_qa",
      'Where an order was placed, were the item, quantity and delivery address confirmed back to the customer?',
      [('pass', 'Item, quantity and address are all confirmed.'),
       ('partial_pass', 'One or two of the three are confirmed.'),
       ('fail', 'An order is placed with none confirmed.'),
       ('NA', 'No order is placed.')]),
    q('gen-103-multiple-issues', "general_qa",
      'Where the customer raised more than one issue, were all of them addressed before the call ended?',
      [('pass', 'Every issue raised is addressed or explicitly deferred with a next step.'),
       ('fail', 'At least one issue raised is dropped without being addressed.'),
       ('NA', 'The customer raises a single issue.')]),
    q('gen-108-taxes-and-fees-included', "general_qa",
      'Where a price was quoted, was it stated whether taxes, fees or delivery were included?',
      [('pass', 'The quote says whether taxes, fees or delivery are included.'),
       ('fail', 'A price is quoted with no indication of what it includes.'),
       ('NA', 'No price is quoted.')]),
    # ---- Taskmaster bookings (assistant / user)
    q('tm-101-party-size', "general_qa",
      'Was the number of people the booking was for confirmed?',
      [('pass', 'The party size is asked for or confirmed.'),
       ('fail', 'A booking is made without establishing the party size.'),
       ('NA', 'The request has no party size (a single ticket, a delivery).')], datasets=["taskmaster"]),
    q('tm-102-date-confirmed', "general_qa",
      'Was the date of the booking confirmed back to the user before it was made?',
      [('pass', 'The date is repeated back or confirmed before booking.'),
       ('fail', 'The booking is made without the date being confirmed.'),
       ('NA', 'No booking is made.')], datasets=["taskmaster"]),
    q('tm-103-unavailable-alternative', "general_qa",
      'When the requested option was unavailable, did the assistant offer an alternative?',
      [('pass', 'At least one alternative is offered.'),
       ('fail', 'The user is told it is unavailable and nothing else.'),
       ('NA', 'Everything requested is available.')], datasets=["taskmaster"]),
    q('tm-104-price-before-booking', "general_qa",
      'Was the price stated before the user was asked to confirm the booking or purchase?',
      [('pass', 'A price is stated before confirmation is sought.'),
       ('fail', 'Confirmation is sought without a price.'),
       ('NA', 'Nothing with a price is booked.')], datasets=["taskmaster"]),
    q('tm-105-name-on-booking', "general_qa",
      'Was the name the booking should be under established?',
      [('pass', 'A name for the booking is asked for or confirmed.'),
       ('fail', 'A booking is made with no name established.'),
       ('NA', 'No booking is made.')], datasets=["taskmaster"]),
    q('tm-106-special-requirements', "general_qa",
      'Where the user mentioned a special requirement (dietary, accessibility, child seat, a particular seat or room), was it acted on?',
      [('pass', 'The requirement is acknowledged and reflected in the booking or the offer.'),
       ('fail', 'The requirement is ignored.'),
       ('NA', 'No special requirement is mentioned.')], datasets=["taskmaster"]),
    q('tm-107-final-confirmation', "general_qa",
      'Did the assistant obtain a clear "yes" from the user before completing the booking?',
      [('pass', 'The user confirms explicitly before the booking is completed.'),
       ('fail', 'The booking is completed without an explicit confirmation.'),
       ('NA', 'No booking is completed.')], datasets=["taskmaster"]),
    q('tm-108-confirmation-details', "general_qa",
      'After booking, did the assistant say how the user would receive confirmation (email, text, reference)?',
      [('pass', 'A confirmation channel or reference is mentioned.'),
       ('fail', 'A booking is completed and nothing is said about confirmation.'),
       ('NA', 'No booking is completed.')], datasets=["taskmaster"]),
    q('tm-109-time-zone-or-location', "general_qa",
      'Where a time was agreed, was any possible ambiguity about it (morning or evening, time zone, which day) resolved?',
      [('pass', 'The time is stated unambiguously or the ambiguity is resolved.'),
       ('fail', 'An ambiguous time is left ambiguous.'),
       ('NA', 'No time is agreed.')], datasets=["taskmaster"]),
    q('tm-110-user-changed-mind', "general_qa",
      'When the user changed their request mid-conversation, did the assistant update accordingly without carrying over the old details?',
      [('pass', 'The change is applied and no stale detail is repeated.'),
       ('fail', 'The assistant repeats or books the old detail after the change.'),
       ('NA', 'The user changes nothing.')], datasets=["taskmaster"]),
    q('tm-111-too-many-questions', "general_qa",
      'Did the assistant ask for information the user had already given?',
      [('fail', 'The assistant asks again for something already stated.'),
       ('pass', 'Nothing already stated is asked for again.')], datasets=["taskmaster"]),
    q('tm-112-options-count', "general_qa",
      'Where several options existed, did the assistant present a manageable number with the key difference between them?',
      [('pass', 'Two to four options are presented with what distinguishes them.'),
       ('partial_pass', 'Options are presented without their differences, or too many at once.'),
       ('fail', 'A single option is imposed although others exist, or the user is overwhelmed with a list.'),
       ('NA', 'Only one option exists.')], datasets=["taskmaster"]),
    q('tm-113-restrictions-stated', "general_qa",
      'Were restrictions on what was booked (non-refundable, age limit, baggage, check-in time, dress code) mentioned?',
      [('pass', 'At least one applicable restriction is mentioned.'),
       ('fail', 'Something with restrictions is booked and none is mentioned.'),
       ('NA', 'Nothing with restrictions is booked.')], datasets=["taskmaster"]),
    q('tm-114-payment-details-handled', "general_qa",
      'Where payment details were needed, did the assistant say how they would be taken rather than asking for them in the conversation?',
      [('pass', 'The assistant explains that payment is taken securely, later, or through a link, or confirms a stored method.'),
       ('fail', 'Card details are requested outright in the conversation.'),
       ('NA', 'No payment is needed.')], datasets=["taskmaster"]),
    q('tm-116-search-narrated', "general_qa",
      'When the assistant needed to look something up, did it say so rather than going silent?',
      [('pass', 'The assistant says it is checking or searching.'),
       ('fail', 'There is an unexplained gap or the result appears with no indication of a search.'),
       ('NA', 'No lookup is needed.')], datasets=["taskmaster"]),
    q('tm-117-user-frustration', "general_qa",
      'Did the user express frustration with the assistant during the conversation?',
      [('fail', 'The user expresses frustration, impatience or annoyance at the assistant.'),
       ('pass', 'No frustration is expressed.')], datasets=["taskmaster"]),
    q('tm-119-location-confirmed', "general_qa",
      'Where a location mattered (pick-up point, restaurant branch, cinema, destination), was it confirmed unambiguously?',
      [('pass', 'The location is stated or confirmed unambiguously.'),
       ('fail', 'An ambiguous location is left unresolved.'),
       ('NA', 'No location matters.')], datasets=["taskmaster"]),
    # ---- ACI-Bench clinical visits (doctor / patient)
    q('aci-51-diagnosis-explained', "general_qa",
      'Was the diagnosis or working diagnosis explained to the patient in plain language?',
      [('pass', 'A diagnosis is named and explained without unexplained jargon.'),
       ('partial_pass', 'A diagnosis is named but not explained, or explained only in technical terms.'),
       ('fail', 'No diagnosis or working diagnosis is shared with the patient.'),
       ('NA', 'The visit is a routine follow-up with no diagnostic question.')], datasets=["aci_bench"]),
    q('aci-52-medication-instructions', "general_qa",
      'Where a medication was started or changed, were the dose, frequency and duration stated?',
      [('pass', 'Dose, frequency and duration are all stated.'),
       ('partial_pass', 'One or two of the three are stated.'),
       ('fail', 'A medication is started or changed with none of the three stated.'),
       ('NA', 'No medication is started or changed.')], datasets=["aci_bench"]),
    q('aci-53-allergies-checked', "general_qa",
      'Before prescribing, did the doctor ask about or confirm allergies?',
      [('pass', 'Allergies are asked about or confirmed before prescribing.'),
       ('fail', 'A prescription is made without any allergy check.'),
       ('NA', 'Nothing is prescribed.')], datasets=["aci_bench"]),
    q('aci-54-current-medications-reviewed', "general_qa",
      "Were the patient's current medications reviewed during the visit?",
      [('pass', 'Current medications are asked about or listed and confirmed.'),
       ('fail', 'Medications are not reviewed although a prescription or a chronic condition is discussed.'),
       ('NA', 'No prescription or chronic condition is discussed.')], datasets=["aci_bench"]),
    q('aci-55-safety-netting', "general_qa",
      'Was the patient told which symptoms should prompt them to seek urgent care or come back sooner?',
      [('pass', 'Specific warning signs and what to do about them are stated.'),
       ('partial_pass', "A vague instruction such as 'come back if it gets worse' is given."),
       ('fail', 'No safety-netting advice is given.')], datasets=["aci_bench"]),
    q('aci-58-shared-decision', "general_qa",
      "Where more than one reasonable course of action existed, was the patient's preference sought before deciding?",
      [('pass', "The doctor asks the patient's preference or view before settling the plan."),
       ('fail', 'The plan is decided without asking the patient.'),
       ('NA', 'Only one reasonable course of action exists.')], datasets=["aci_bench"]),
    q('aci-59-lifestyle-advice', "general_qa",
      'Where lifestyle factors (diet, exercise, smoking, alcohol, sleep) were relevant to the problem, were they discussed?',
      [('pass', 'At least one relevant lifestyle factor is discussed with advice.'),
       ('fail', 'A problem with an obvious lifestyle component is discussed with no lifestyle advice.'),
       ('NA', 'Lifestyle factors are not relevant to the problem.')], datasets=["aci_bench"]),
    q('aci-60-mental-health-asked', "general_qa",
      "Where the patient's account suggested stress, low mood or anxiety, did the doctor ask about it?",
      [('pass', 'The doctor asks about mood, stress or anxiety.'),
       ('fail', 'Cues of stress, low mood or anxiety are present and not followed up.'),
       ('NA', 'No such cues are present.')], datasets=["aci_bench"]),
    q('aci-61-red-flags-asked', "general_qa",
      'Did the doctor ask about serious-symptom red flags relevant to the presenting complaint?',
      [('pass', 'At least one relevant red-flag question is asked (for example chest pain with breathlessness, headache with vision change).'),
       ('fail', 'A presenting complaint with well-known red flags is assessed without asking about any of them.'),
       ('NA', 'The presenting complaint has no relevant red flags.')], datasets=["aci_bench"]),
    q('aci-62-symptom-history', "general_qa",
      'Was the history of the presenting symptom taken in reasonable detail (onset, duration, severity, what makes it better or worse)?',
      [('pass', 'At least three of onset, duration, severity and modifying factors are covered.'),
       ('partial_pass', 'One or two are covered.'),
       ('fail', 'The symptom is accepted with no history taken.'),
       ('NA', 'There is no presenting symptom (routine review).')], datasets=["aci_bench"]),
    q('aci-63-tests-explained', "general_qa",
      'Where a test or investigation was ordered, was the patient told what it was for?',
      [('pass', 'The purpose of each test is explained.'),
       ('partial_pass', 'Some tests are explained, others not.'),
       ('fail', 'Tests are ordered with no explanation.'),
       ('NA', 'No test is ordered.')], datasets=["aci_bench"]),
    q('aci-64-referral-explained', "general_qa",
      'Where a referral was made, was the patient told who they were being referred to and why?',
      [('pass', 'The specialty or service and the reason are stated.'),
       ('partial_pass', 'One of the two is stated.'),
       ('fail', 'A referral is made with no explanation.'),
       ('NA', 'No referral is made.')], datasets=["aci_bench"]),
    q('aci-65-time-to-improvement', "general_qa",
      'Was the patient told how long the treatment should take to work, or when to expect improvement?',
      [('pass', 'A timescale for improvement is given.'),
       ('fail', 'A treatment is started with no indication of when it should help.'),
       ('NA', 'No treatment is started.')], datasets=["aci_bench"]),
    q('aci-66-patient-interrupted', "general_qa",
      'Did the doctor interrupt the patient while they were describing their problem?',
      [('fail', "The doctor cuts across the patient's account more than once, or once at a material moment."),
       ('pass', 'The patient is allowed to finish.')], datasets=["aci_bench"]),
    q('aci-69-work-or-activity-advice', "general_qa",
      'Was the patient told what they could or should not do (work, driving, sport, lifting) while recovering?',
      [('pass', 'Activity advice is given.'),
       ('fail', 'A condition that restricts activity is discussed with no advice.'),
       ('NA', 'The condition does not restrict activity.')], datasets=["aci_bench"]),
    q('aci-70-previous-treatment-asked', "general_qa",
      'Did the doctor ask what the patient had already tried for the problem?',
      [('pass', 'The doctor asks about previous treatments or self-care.'),
       ('fail', 'The doctor does not ask.'),
       ('NA', 'There is no problem for which prior treatment would apply.')], datasets=["aci_bench"]),
    q('aci-71-jargon-unexplained', "general_qa",
      'Did the doctor use medical terms without explaining them to the patient?',
      [('fail', 'At least one medical term is used with no explanation and no sign the patient knew it.'),
       ('pass', 'Medical terms are explained, or none are used.')], datasets=["aci_bench"]),
    q('aci-73-visit-closed', "general_qa",
      'Did the visit end with a clear close (a summary, next appointment or goodbye) from the doctor?',
      [('pass', 'A clear close is given.'),
       ('fail', 'The transcript ends with no close from the doctor.')], datasets=["aci_bench"]),
    q('aci-74-patient-questions-answered', "general_qa",
      "Were the patient's questions answered rather than deflected?",
      [('pass', 'Every question the patient asks receives a direct answer.'),
       ('partial_pass', 'Some questions are answered, others deflected or ignored.'),
       ('fail', 'The patient\'s questions are deflected or ignored.'),
       ('NA', 'The patient asks no questions.')], datasets=["aci_bench"]),
    q('aci-75-empathy-statement', "general_qa",
      'Did the doctor make at least one empathic statement (acknowledging pain, difficulty or worry)?',
      [('pass', 'At least one empathic statement is made.'),
       ('fail', 'No empathic statement is made although the patient describes pain, difficulty or worry.'),
       ('NA', 'The patient describes no pain, difficulty or worry.')], datasets=["aci_bench"]),
    q('aci-76-vaccination-or-screening', "general_qa",
      'Did the doctor raise preventive care (vaccination, screening, check-ups) during the visit?',
      [('pass', 'Preventive care is raised.'),
       ('fail', 'Preventive care is not raised.')], datasets=["aci_bench"]),
    q('aci-cmp-02-acknowledged', "complaint",
      'Where the patient complained about their care or the service, did the doctor acknowledge it?',
      [('pass', 'The complaint is acknowledged in words.'),
       ('fail', 'The complaint is passed over.'),
       ('NA', 'No complaint is raised.')], datasets=["aci_bench"]),
    # ---- SPoRC podcasts: host behaviour (host / other speakers)
    q('hst-10-conflict-disclosed', "general_qa",
      'Where the host had a personal or financial interest in something discussed, was it disclosed?',
      [('pass', 'The interest is disclosed.'),
       ('fail', 'An interest is evident (the host sells, is paid by, or is affiliated with what is discussed) and not disclosed.'),
       ('NA', 'No such interest is evident.')], datasets=["sporc"]),
    q('hst-11-guest-corrected', "general_qa",
      "When a guest said something clearly wrong or unsupported, did the host query or correct it?",
      [('pass', 'The host queries or corrects it.'),
       ('fail', 'The host lets it stand or endorses it.'),
       ('NA', 'No guest says anything clearly wrong or unsupported.')], datasets=["sporc"]),
    q('hst-12-leading-questions', "general_qa",
      "Did the host mostly ask open questions rather than leading ones that contain the expected answer?",
      [('pass', 'Most questions are open.'),
       ('partial_pass', 'A mix of open and leading questions.'),
       ('fail', 'Most questions are leading.'),
       ('NA', 'The host asks no questions.')], datasets=["sporc"]),
    q('hst-13-balance-on-controversy', "general_qa",
      'Where a contested topic was discussed, did the host present or acknowledge more than one view?',
      [('pass', 'Another view is presented or acknowledged.'),
       ('fail', 'Only one view is given and presented as settled.'),
       ('NA', 'No contested topic is discussed.')], datasets=["sporc"]),
    q('hst-14-opinion-as-opinion', "general_qa",
      'When the host gave an opinion, was it marked as an opinion rather than stated as fact?',
      [('pass', 'Opinions are signalled as such.'),
       ('fail', 'Opinions are stated as facts.'),
       ('NA', 'The host gives no opinion.')], datasets=["sporc"]),
    q('hst-15-content-warning', "general_qa",
      'Where the episode covered distressing or explicit material, did the host give a warning beforehand?',
      [('pass', 'A warning is given before the material.'),
       ('fail', 'Distressing or explicit material is covered with no warning.'),
       ('NA', 'No such material is covered.')], datasets=["sporc"]),
    q('hst-16-sponsor-separated', "general_qa",
      'Where a sponsor message was read, was it clearly separated from the editorial content?',
      [('pass', 'The sponsor message is introduced or closed as such, separating it from the discussion.'),
       ('fail', 'Sponsor content is blended into the discussion without signalling.'),
       ('NA', 'No sponsor message is read.')], datasets=["sporc"]),
    q('hst-17-guest-thanked', "general_qa",
      'Did the host thank the guest and say where listeners could find them or their work?',
      [('pass', 'The guest is thanked and their work or contact is pointed to.'),
       ('partial_pass', 'The guest is thanked without any pointer.'),
       ('fail', 'The guest is neither thanked nor pointed to.'),
       ('NA', 'There is no guest.')], datasets=["sporc"]),
    q('hst-18-episode-context', "general_qa",
      'Did the host tell listeners when or in what context the episode was recorded, where that mattered?',
      [('pass', 'A date or context is given.'),
       ('fail', 'Time-sensitive matters are discussed with no indication of when.'),
       ('NA', 'Nothing time-sensitive is discussed.')], datasets=["sporc"]),
    q('hst-19-listener-action-explained', "general_qa",
      'Where the host asked listeners to do something (subscribe, review, donate), was it a brief ask rather than a prolonged one?',
      [('pass', 'The ask is brief.'),
       ('fail', 'The ask is prolonged or repeated several times.'),
       ('NA', 'No ask is made.')], datasets=["sporc"]),
    q('hst-20-personal-info-third-party', "general_qa",
      'Did the host share identifying personal information about a third party who was not present?',
      [('fail', 'Identifying private details about an absent third party are shared.'),
       ('pass', 'No such details are shared.')], datasets=["sporc"]),
    q('hst-21-host-preparation', "general_qa",
      "Did the host show they had prepared (referring to the guest's work, prior statements or specifics of the topic)?",
      [('pass', 'The host refers to specifics that show preparation.'),
       ('fail', 'The host shows no sign of preparation.'),
       ('NA', 'The episode has no guest and no researched topic.')], datasets=["sporc"]),
    q('hst-22-time-management', "general_qa",
      'Did the host manage the episode so that the main topic was reached and covered rather than lost in preamble?',
      [('pass', 'The main topic is reached promptly and covered.'),
       ('partial_pass', 'The main topic is reached late but covered.'),
       ('fail', 'The main topic is barely reached.')], datasets=["sporc"]),
    q('hst-23-host-talks-over-guest', "general_qa",
      'Did the host talk over or cut off a guest mid-answer?',
      [('fail', 'The host cuts off a guest more than once, or once at a material point.'),
       ('pass', 'Guests finish their answers.'),
       ('NA', 'There is no guest.')], datasets=["sporc"]),
    # ---- SPoRC podcasts: any speaker
    q('spk-27-statistics-sourced', "general_qa",
      'When a statistic or number was cited, was its source given?',
      [('pass', 'Sources are given for the statistics cited.'),
       ('partial_pass', 'Some statistics are sourced, others not.'),
       ('fail', 'Statistics are cited with no source.'),
       ('NA', 'No statistic is cited.')], datasets=["sporc"]),
    q('spk-28-acronyms-explained', "general_qa",
      'Were acronyms and abbreviations explained on first use?',
      [('pass', 'Acronyms are explained on first use.'),
       ('partial_pass', 'Some are explained, others not.'),
       ('fail', 'Acronyms are used without explanation.'),
       ('NA', 'No acronym is used.')], datasets=["sporc"]),
    q('spk-29-personal-disclosure', "general_qa",
      'Did any speaker disclose a personal matter (health, family, finances) about themselves?',
      [('fail', 'A speaker discloses a personal matter about themselves.'),
       ('pass', 'No personal matter is disclosed.')], datasets=["sporc"]),
    q('spk-30-medical-or-legal-claim', "general_qa",
      'Did any speaker make a specific medical, legal or financial claim that listeners might act on?',
      [('fail', 'Such a claim is made.'),
       ('pass', 'No such claim is made.')], datasets=["sporc"]),
    q('spk-31-humour-at-expense', "general_qa",
      'Was humour used at the expense of a group or an absent individual?',
      [('fail', 'Humour targets a group or an absent individual.'),
       ('pass', 'No such humour occurs.')], datasets=["sporc"]),
    q('spk-32-speaker-name-established', "general_qa",
      'Can each main speaker be identified by name from the episode itself?',
      [('pass', 'Every main speaker is named at some point.'),
       ('partial_pass', 'Some main speakers are named.'),
       ('fail', 'No speaker is named.')], datasets=["sporc"]),
    q('spk-33-repetition', "general_qa",
      'Did the conversation repeat the same point several times without adding anything?',
      [('fail', 'A point is repeated three or more times with nothing added.'),
       ('pass', 'Points are made once or developed when repeated.')], datasets=["sporc"]),
    q('spk-34-recommendation-caveated', "general_qa",
      'When a product, book or service was recommended, was any downside or caveat mentioned?',
      [('pass', 'A caveat accompanies the recommendation.'),
       ('fail', 'Recommendations are unqualified.'),
       ('NA', 'Nothing is recommended.')], datasets=["sporc"]),
    q('spk-35-audience-assumed', "general_qa",
      "Did the speakers assume knowledge the audience might not have, without filling it in?",
      [('fail', 'Background is assumed and never filled in.'),
       ('partial_pass', 'Some background is filled in, some assumed.'),
       ('pass', 'Background is filled in where needed.')], datasets=["sporc"]),
    q('spk-36-question-dodged', "general_qa",
      'Did a speaker dodge a direct question rather than answer it?',
      [('fail', 'A direct question is dodged.'),
       ('pass', 'Direct questions are answered.'),
       ('NA', 'No direct question is asked.')], datasets=["sporc"]),
]

assert len({x.id for x in QUESTIONS}) == len(QUESTIONS), "duplicate question ids"


def all_questions(labelled_path: Path = OUT_DIR / "labelled_data.jsonl") -> list[Question]:
    """The bank plus every distinct question embedded in the labelled data."""
    seen = {x.id for x in QUESTIONS}
    out = list(QUESTIONS)
    if labelled_path.exists():
        for line in labelled_path.open():
            qd = json.loads(line)["question"]
            if qd["id"] not in seen:
                seen.add(qd["id"])
                out.append(Question.model_validate(qd))
    return out

# Taskmaster counterparts: the family questions and the conduct questions the audit found meaningful there.
TM_FROM = ["vul-01-present", "vul-02-handled", "cmp-01-complaint", "eod-01-dissatisfaction"] + [
    f"gen-{n}" for n in ("04-address", "05-contact-details", "06-data-protection", "07-needs-established", "08-affordability",
                         "09-open-questions", "10-costs-explained", "12-key-terms", "13-cancellation-rights", "14-alternatives",
                         "15-timescales", "16-read-back", "17-customer-actions", "19-name-use", "20-questions-invited",
                         "21-next-steps", "23-explicit-consent", "25-confirmation-to-follow", "26-full-name",
                         "28-clarifying-question", "29-preference-honoured", "30-availability-checked", "31-decline-explained",
                         "32-total-amount", "33-payment-method", "34-date-time-quoted", "35-conditions-mentioned",
                         "37-mistake-corrected", "39-recap-of-agreement", "40-further-help-offered", "41-contact-route",
                         "45-option-comparison", "46-email-or-number-readback", "47-expectation-set",
                         "49-hold-or-wait-explained", "50-spelling-confirmed",
                         # bank v3 conduct questions that apply to bookings as well
                         "60-customer-decline-respected",                          "70-numbers-accurate", "76-ownership",                          "82-active-listening", "90-promise-kept-in-call")]
_by_id = {x.id: x for x in QUESTIONS}
QUESTIONS += [tm_variant(_by_id[i]) for i in TM_FROM]


def write_questions(labelled_path: Path = OUT_DIR / "labelled_data.jsonl",
                    out_path: Path = OUT_DIR / "questions.jsonl") -> int:
    qs = all_questions(labelled_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        for x in qs:
            f.write(x.model_dump_json() + "\n")
    return len(qs)


if __name__ == "__main__":
    from collections import Counter
    n = write_questions()
    print(f"wrote {n} questions ({len(QUESTIONS)} bank) -> {OUT_DIR / 'questions.jsonl'}")
    print(Counter(x.family for x in QUESTIONS))
