"""The question bank: reusable questions that apply to any call. This module is
the source of truth for them. data/labelled_data/questions.jsonl is derived from it
(plus any question found only in labelled_data.jsonl, for forward compatibility).

Original questions in the generic shape of regulated-industry call QA. Four
families: vulnerability (two questions: is a characteristic present, tagged
with the FCA FG21/1 characteristic(s); and did the agent handle it), complaint
(a stated problem with a sought resolution), eod (expression of dissatisfaction,
broader than a complaint), and general_qa (call-observable conduct). For the
detection questions `fail` means "the thing was detected", matching how such
questions are scored in practice. Every question carries pass and fail;
partial_pass and NA are optional per question.

Run: uv run python -m src.synthesis.question_bank   (regenerates questions.jsonl)
"""

import json
import re
from pathlib import Path

from src.synthesis.schema import Question

OUT_DIR = Path(__file__).resolve().parents[2] / "data" / "labelled_data"


# Every question is written in the speaker vocabulary of the transcripts it is asked of
# (decision 2026-09-03): AppTek calls have `agent`/`customer`, Taskmaster conversations
# `assistant`/`user`, ACI-Bench visits `doctor`/`patient`, SPoRC episodes `host` plus
# diarisation tags. A question is shared across corpora only when its wording already
# applies verbatim (the role-agnostic `spk-` set, phrased in terms of "the speakers").
# `gen-` and the four family questions are AppTek's; `tm-` and `aci-` are their
# Taskmaster and ACI-Bench counterparts, dataset-specific by construction; `hst-` are
# SPoRC host-behaviour questions.
ALL = ["apptek", "taskmaster", "aci_bench", "sporc"]


def q(id, family, text, options, description="", tags=None, datasets=("apptek",)):
    return Question(
        id=id, source="bank", family=family, text=text, description=description,
        options=[{"value": v, "criteria": c} for v, c in options], tags=tags or [],
        dataset_allow_list=list(datasets),
    )


# Taskmaster's assistant/user conversations: the same conduct as the AppTek questions in the
# corpus's own vocabulary. Derived by substitution because the behaviours are identical; the
# derived text is what questions.jsonl records.
TM_WORDS = [(r"\bagent's\b", "assistant's"), (r"\bAgent's\b", "Assistant's"), (r"\bagent\b", "assistant"),
            (r"\bAgent\b", "Assistant"), (r"\bcustomer's\b", "user's"), (r"\bCustomer's\b", "User's"),
            (r"\bcustomer\b", "user"), (r"\bCustomer\b", "User"), (r"\bcall\b", "conversation")]


def _tm(text: str) -> str:
    for pat, rep in TM_WORDS:
        text = re.sub(pat, rep, text)
    return text


def tm_variant(base: Question) -> Question:
    """The Taskmaster counterpart of an AppTek question: id gen-NN-x -> tm-NN-x, vocabulary swapped."""
    return Question(
        id=re.sub(r"^(gen|vul|cmp|eod)-", lambda m: f"tm-{m.group(1)}-" if m.group(1) != "gen" else "tm-", base.id),
        source="bank", family=base.family, text=_tm(base.text), description=_tm(base.description),
        options=[{"value": o.value, "criteria": _tm(o.criteria)} for o in base.options], tags=base.tags,
        dataset_allow_list=["taskmaster"],
    )



# The FCA's published characteristics of vulnerability (FG21/1, Figure 1), used as the
# closed tag vocabulary for the vulnerability questions.
FCA_TAGS = ['physical disability', 'severe or long-term illness', 'hearing or visual impairment', 'mental health condition', 'addiction', 'low mental capacity or cognitive disability', 'retirement', 'bereavement', 'income shock', 'relationship breakdown', 'domestic abuse', 'caring responsibilities', 'other significant life circumstances', 'inadequate or erratic income', 'over-indebtedness', 'low savings', 'low emotional resilience', 'low knowledge or confidence in managing finances', 'poor literacy or numeracy', 'poor English language skills', 'poor or no digital skills', 'learning difficulties', 'no or low access to help or support']

VUL_DESC = "A characteristic of vulnerability is a personal circumstance that makes the customer especially susceptible to harm, particularly when a firm does not act with appropriate care. The FCA's guidance (FG21/1) groups them under four drivers: health (a condition or illness affecting the ability to carry out day-to-day tasks), life events (bereavement, job loss, relationship breakdown and similar), resilience (low ability to withstand financial or emotional shocks) and capability (low knowledge or confidence in managing finances, or low literacy, numeracy or digital skills). Vulnerability is about the customer's circumstances, not about a complaint or a bad outcome. Answer fail when such a characteristic is disclosed or clearly evident, and tag every characteristic present."


QUESTIONS: list[Question] = [
    q("vul-01-present", "vulnerability",
      "Does the customer show a characteristic of vulnerability during the call?",
      [("fail", "Clear indicators of vulnerability are present: the customer discloses or clearly displays a health condition, a significant life event, low financial resilience, or low capability to understand or manage the matter."),
       ("pass", "No indicator of vulnerability is present; the customer appears engaged, informed and capable throughout.")],
      description=VUL_DESC, tags=FCA_TAGS, datasets=["apptek"]),
    q("vul-02-handled", "vulnerability",
      "Where the customer showed a characteristic of vulnerability, did the agent recognise it and respond appropriately?",
      [("pass", "The agent acknowledges the vulnerability and responds to it: adapts tone, pace or explanation, offers extra time or a follow-up in writing, involves a trusted person, or signposts relevant support."),
       ("fail", "The agent does not appropriately address the vulnerability: continues with a standard script, ignores or brushes past the disclosure, or responds in a way that could add to the customer's difficulty."),
       ("NA", "The customer shows no characteristic of vulnerability.")],
      description=("Judge only the agent's handling of vulnerability the customer actually displayed. Evidence should be the agent's "
                   "responses to the customer's disclosure (or the points where a response was conspicuously missing), plus the "
                   "disclosure itself; general conduct elsewhere in the call is not relevant."),
      tags=FCA_TAGS, datasets=["apptek"]),
    q("cmp-01-complaint", "complaint",
      "Does the customer make a complaint during the call?",
      [("fail", "The customer makes a clear complaint and expects a resolution: they explicitly state a problem with the service, product or experience and ask for, or clearly expect, it to be put right."),
       ("pass", "No complaint is made. The customer may express mild frustration, but does not state a problem and seek a resolution.")],
      description=("A complaint is an expression of a problem, formal or informal, together with a request or expectation that it be "
                   "resolved. Frustration on its own is not a complaint; a complaint has a stated problem and a sought outcome."), datasets=["apptek"]),
    q("eod-01-dissatisfaction", "eod",
      "Does the customer express dissatisfaction during the call?",
      [("fail", "The customer clearly expresses unhappiness, frustration or dissatisfaction with the service, product, process or outcome."),
       ("pass", "The customer is satisfied or neutral throughout; no dissatisfaction is expressed.")],
      description=("An expression of dissatisfaction is any clear statement of unhappiness with how they have been treated, what they "
                   "received, how the process went or what the outcome was, whether or not they ask for anything to be done about "
                   "it. It is broader than a complaint: every complaint contains dissatisfaction, but dissatisfaction without a "
                   "sought resolution is not a complaint."), datasets=["apptek"]),
    q('gen-01-introduction', "general_qa",
      'Did the agent introduce themselves by name and state which organisation they represent?',
      [('pass', "Both the agent's name and the organisation are stated in the opening."),
       ('partial_pass', 'One of the two is stated but not both.'),
       ('fail', 'Neither is stated.')]),
    q('gen-02-account-holder', "general_qa",
      'Did the agent confirm they were speaking with the account holder or an authorised person before discussing the account?',
      [('pass', 'The agent confirms who they are speaking to before any account-specific information is shared.'),
       ('fail', 'Account-specific information is shared without confirming who is on the line.'),
       ('NA', 'No account or personal record is discussed.')]),
    q('gen-03-identity-verification', "general_qa",
      "Was the customer's identity verified before account details were discussed?",
      [('pass', 'At least two identifying details are requested and confirmed before any account-specific information is given.'),
       ('partial_pass', 'Only one identifying detail is checked, or verification happens after account details have already been discussed.'),
       ('fail', 'No identity verification takes place.'),
       ('NA', 'No account-specific information is discussed.')]),
    q('gen-04-address', "general_qa",
      "Was the customer's address confirmed during the call?",
      [('pass', 'The address, or its first line and postcode, is asked for and confirmed.'),
       ('fail', 'The address is never confirmed.'),
       ('NA', 'The call has no reason to confirm an address.')]),
    q('gen-05-contact-details', "general_qa",
      "Were the customer's contact details (phone number or email) confirmed or updated?",
      [('pass', 'A phone number or email address is confirmed or taken down.'),
       ('fail', 'Contact details are needed for a follow-up but never confirmed.'),
       ('NA', 'No follow-up contact is required.')]),
    q('gen-06-data-protection', "general_qa",
      "Did the agent explain, or obtain agreement to, how the customer's personal information would be used?",
      [('pass', 'The agent states how the information will be used or stored and the customer acknowledges it.'),
       ('fail', 'Personal information is collected without any explanation or acknowledgement.'),
       ('NA', 'No personal information beyond a name is collected.')]),
    q('gen-07-needs-established', "general_qa",
      "Did the agent establish the customer's specific needs before recommending anything?",
      [('pass', "The agent asks about the customer's situation and requirements and reflects them back before recommending."),
       ('partial_pass', 'Some needs are explored but the recommendation is made before they are confirmed.'),
       ('fail', 'A recommendation is made without exploring needs.'),
       ('NA', 'Nothing is recommended on the call.')]),
    q('gen-08-affordability', "general_qa",
      'Where a cost or ongoing payment was involved, did the agent check that the customer could afford it?',
      [('pass', "The agent asks about the customer's ability to pay before agreeing the cost."),
       ('fail', 'A cost is agreed without any affordability check.'),
       ('NA', 'No cost or payment is involved.')]),
    q('gen-09-open-questions', "general_qa",
      "Did the agent use open questions to understand the customer's situation, rather than only closed or leading questions?",
      [('pass', 'The agent asks open questions and lets the customer describe their situation.'),
       ('partial_pass', 'A mix, with leading questions steering some answers.'),
       ('fail', 'The agent relies on leading or closed questions throughout.')]),
    q('gen-10-costs-explained', "general_qa",
      'Were all costs, fees or charges the customer would incur stated clearly?',
      [('pass', 'Every applicable cost is stated with its amount or basis before the customer commits.'),
       ('partial_pass', 'Costs are mentioned but amounts or conditions are vague.'),
       ('fail', 'A cost the customer will incur is not mentioned.'),
       ('NA', 'No cost applies.')]),
    q('gen-11-risks-limitations', "general_qa",
      'Were the risks, limitations or downsides of the product or option discussed made clear?',
      [('pass', 'The agent states what the customer could lose, what is excluded, or what the option cannot do.'),
       ('partial_pass', 'Limitations are alluded to but not explained.'),
       ('fail', 'Only benefits are described.'),
       ('NA', 'No product or option is discussed.')]),
    q('gen-12-key-terms', "general_qa",
      'Were the key terms of what was agreed (what, how much, when, for how long) stated before the customer committed?',
      [('pass', 'All key terms are stated before commitment.'),
       ('partial_pass', 'Most terms are stated; at least one material term is omitted.'),
       ('fail', 'The customer commits without the key terms being stated.'),
       ('NA', 'The customer does not commit to anything.')]),
    q('gen-13-cancellation-rights', "general_qa",
      'Where the customer agreed to a product or service, was their right to cancel or cooling-off period explained?',
      [('pass', 'The cancellation right and its period are stated.'),
       ('fail', 'The customer agrees to something without being told how or whether they can cancel.'),
       ('NA', 'The customer does not agree to a product or service.')]),
    q('gen-14-alternatives', "general_qa",
      'Were alternative options presented, or the reason for recommending one option over others explained?',
      [('pass', 'At least one alternative is mentioned, or the choice is justified against alternatives.'),
       ('fail', 'A single option is presented as the only one with no justification.'),
       ('NA', 'No recommendation is made.')]),
    q('gen-15-timescales', "general_qa",
      'Where something was to happen after the call, was the customer given a specific timescale?',
      [('pass', 'A specific timescale (day, date or period) is given.'),
       ('partial_pass', "A vague timescale such as 'soon' or 'shortly' is given."),
       ('fail', 'No timescale is given.'),
       ('NA', 'Nothing is to happen after the call.')]),
    q('gen-16-read-back', "general_qa",
      'Were important details the customer provided read back to confirm they were captured correctly?',
      [('pass', 'Details such as numbers, spellings or dates are repeated back and confirmed.'),
       ('fail', 'Important details are taken down without confirmation.'),
       ('NA', 'No important details are provided.')]),
    q('gen-17-customer-actions', "general_qa",
      'Was the customer told what they themselves needed to do after the call (send documents, complete a form, make a payment, attend somewhere)?',
      [('pass', "The customer's own required actions are stated clearly."),
       ('partial_pass', 'An action is implied but not spelled out (what, how or by when is missing).'),
       ('fail', 'The customer has something to do but is not told.'),
       ('NA', 'Nothing is required of the customer after the call.')]),
    q('gen-18-empathy', "general_qa",
      'Where the customer expressed frustration, worry or disappointment, did the agent acknowledge it?',
      [('pass', "The agent acknowledges the customer's feeling before moving on."),
       ('fail', 'The feeling is ignored or dismissed.'),
       ('NA', 'The customer expresses no such feeling.')]),
    q('gen-19-name-use', "general_qa",
      "Did the agent use the customer's name at least once after the opening?",
      [('pass', 'The customer is addressed by name during the call, not only in the greeting.'),
       ('fail', "The customer's name is not used after the opening."),
       ('NA', "The customer's name is never established.")]),
    q('gen-20-questions-invited', "general_qa",
      'Was the customer given an opportunity to ask questions before the call ended?',
      [('pass', 'The agent explicitly asks whether the customer has any questions or needs anything else.'),
       ('fail', 'The call is closed without any such invitation.')]),
    q('gen-21-next-steps', "general_qa",
      'Were the next steps summarised before the call ended, including who does what and by when?',
      [('pass', 'What happens next, who is responsible and when are all stated.'),
       ('partial_pass', 'Next steps are mentioned without who or when.'),
       ('fail', 'No next steps are stated.'),
       ('NA', 'Nothing follows from the call.')]),
    q('gen-22-eligibility-explained', "general_qa",
      'Were the eligibility requirements or qualifying conditions for what the customer wanted explained?',
      [('pass', 'The conditions the customer must meet are stated before proceeding.'),
       ('partial_pass', 'Conditions are mentioned only in part or only when the customer asks.'),
       ('fail', 'The agent proceeds without stating conditions that apply.'),
       ('NA', 'Nothing discussed carries eligibility conditions.')]),
    q('gen-23-explicit-consent', "general_qa",
      "Did the agent obtain the customer's explicit agreement before actioning a change or purchase?",
      [('pass', 'The agent describes the change and the customer clearly agrees before it is actioned.'),
       ('fail', 'A change is actioned without clear agreement, or agreement is assumed.'),
       ('NA', 'No change or purchase is actioned.')]),
    q('gen-24-marketing-preferences', "general_qa",
      "Where the customer's details were being recorded for the first time, were their marketing or contact preferences asked?",
      [('pass', 'The agent asks how, or whether, the customer wishes to be contacted for marketing.'),
       ('fail', 'Details are recorded without asking preferences.'),
       ('NA', 'No new customer record is created.')]),
    q('gen-25-confirmation-to-follow', "general_qa",
      'Did the agent say that written confirmation would follow, and how?',
      [('pass', 'The agent states that confirmation will be sent and by what channel.'),
       ('fail', 'Something is agreed but no confirmation is offered.'),
       ('NA', 'Nothing requiring confirmation is agreed.')]),
    q('gen-26-full-name', "general_qa",
      "Did the agent establish the customer's full name?",
      [('pass', 'Both first name and surname are asked for or confirmed.'),
       ('partial_pass', 'Only a first name is established.'),
       ('fail', 'No name is established.')]),
    q('gen-27-reference-asked', "general_qa",
      "Did the agent ask for an account, booking, policy or order reference to locate the customer's record?",
      [('pass', 'A reference of that kind is requested and provided.'),
       ('fail', 'The agent proceeds without asking for one although the request concerns an existing record.'),
       ('NA', 'The request concerns no existing record.')]),
    q('gen-28-clarifying-question', "general_qa",
      "Where the customer's request was ambiguous or incomplete, did the agent ask a clarifying question before acting?",
      [('pass', 'The agent asks at least one clarifying question that narrows the request.'),
       ('fail', 'The agent acts on an assumption without clarifying.'),
       ('NA', 'The request is specific from the outset.')]),
    q('gen-29-preference-honoured', "general_qa",
      'Were the constraints the customer stated (dates, budget, location, dietary or similar) reflected in what the agent offered?',
      [('pass', 'Every stated constraint is respected in the offer.'),
       ('partial_pass', 'Some constraints are respected; at least one is ignored without acknowledgement.'),
       ('fail', "The offer disregards the customer's stated constraints."),
       ('NA', 'The customer states no constraints.')]),
    q('gen-30-availability-checked', "general_qa",
      'Did the agent check availability, eligibility or stock before confirming that something could be done?',
      [('pass', 'The agent checks (or says they are checking) before confirming.'),
       ('fail', 'The agent confirms without checking and is later corrected, or never checks.'),
       ('NA', 'Nothing is confirmed that would require a check.')]),
    q('gen-31-decline-explained', "general_qa",
      'Where the agent could not meet a request, did they explain why?',
      [('pass', 'A specific reason is given for what cannot be done.'),
       ('partial_pass', "A vague reason such as 'policy' with no detail."),
       ('fail', 'The request is declined with no reason.'),
       ('NA', 'Every request is met.')]),
    q('gen-32-total-amount', "general_qa",
      'Was the total amount the customer would pay stated before they agreed to it?',
      [('pass', 'A total figure is stated before agreement.'),
       ('partial_pass', 'Components are given but no total.'),
       ('fail', 'The customer agrees without any figure.'),
       ('NA', 'No payment is involved.')]),
    q('gen-33-payment-method', "general_qa",
      'Was the method or timing of payment confirmed with the customer?',
      [('pass', 'How and when payment is taken is stated and acknowledged.'),
       ('fail', 'Payment is arranged without confirming method or timing.'),
       ('NA', 'No payment is involved.')]),
    q('gen-34-date-time-quoted', "general_qa",
      'Where a delivery, appointment, arrival or completion was arranged, was a specific date or time quoted?',
      [('pass', 'A specific date and/or time is quoted.'),
       ('partial_pass', 'Only an approximate window is quoted.'),
       ('fail', 'No date or time is quoted.'),
       ('NA', 'Nothing is arranged for a future date.')]),
    q('gen-35-conditions-mentioned', "general_qa",
      'Did the agent proactively mention a relevant condition, restriction or exclusion that the customer had not asked about?',
      [('pass', 'At least one relevant condition is volunteered.'),
       ('fail', 'Conditions are only stated when the customer asks, or not at all.'),
       ('NA', 'No conditions apply to what is discussed.')]),
    q('gen-36-deadline-mentioned', "general_qa",
      'Where a deadline, expiry or time limit applied to the customer, was it stated?',
      [('pass', 'The deadline or time limit is stated with a date or period.'),
       ('partial_pass', 'A deadline is mentioned without saying when.'),
       ('fail', 'A deadline applies but is not mentioned.'),
       ('NA', 'No deadline or time limit applies.')]),
    q('gen-37-mistake-corrected', "general_qa",
      'Did the customer have to correct the agent about a detail during the call?',
      [('pass', "The customer corrects no detail; the agent's details are right first time."),
       ('partial_pass', 'The customer corrects one detail and the agent accepts it.'),
       ('fail', 'The customer corrects the agent more than once, or a correction is resisted.')]),
    q('gen-39-recap-of-agreement', "general_qa",
      'Did the agent recap what had been agreed (order, booking, change) before ending the call?',
      [('pass', 'The agent restates the agreed details and the customer confirms.'),
       ('partial_pass', 'A partial recap that omits at least one agreed detail.'),
       ('fail', 'No recap is given.'),
       ('NA', 'Nothing is agreed.')]),
    q('gen-40-further-help-offered', "general_qa",
      'Did the agent offer relevant additional help or options beyond the immediate request?',
      [('pass', 'A relevant further option or piece of help is offered.'),
       ('fail', 'Only the immediate request is handled.'),
       ('NA', 'The call ends before such an offer would be reasonable.')]),
    q('gen-41-contact-route', "general_qa",
      'Was the customer told how to get back in touch if they needed to (number, channel, hours or a named contact)?',
      [('pass', 'A specific way to make contact is given.'),
       ('fail', 'The customer is left without a route to follow up.'),
       ('NA', 'No follow-up could be needed.')]),
    q('gen-43-existing-customer-check', "general_qa",
      'Did the agent establish whether the customer already had a relationship with the organisation (an existing account, booking or policy)?',
      [('pass', 'The agent asks or confirms whether the customer is an existing customer.'),
       ('fail', 'The agent assumes one way or the other without asking.'),
       ('NA', 'The question is irrelevant to the request.')]),
    q('gen-44-personal-questions-explained', "general_qa",
      'When asking for personal or financial details, did the agent explain why they were needed?',
      [('pass', 'A reason is given for each request for personal or financial detail.'),
       ('partial_pass', 'A reason is given for some requests but not others.'),
       ('fail', 'Details are requested with no reason.'),
       ('NA', 'No personal or financial details are requested.')]),
    q('gen-45-option-comparison', "general_qa",
      'Where more than one option was presented, were the differences between them explained?',
      [('pass', 'The agent explains how the options differ on price, features or suitability.'),
       ('partial_pass', 'Options are listed with little or no comparison.'),
       ('fail', 'The customer is left to work out the differences.'),
       ('NA', 'Only one option is presented.')]),
    q('gen-46-email-or-number-readback', "general_qa",
      'Where an email address or phone number was provided, was it read back for confirmation?',
      [('pass', 'The email or number is repeated back and confirmed.'),
       ('fail', 'It is taken without being read back.'),
       ('NA', 'No email address or phone number is provided.')]),
    q('gen-47-expectation-set', "general_qa",
      "Did the agent set the customer's expectations about what would happen if the request could not be completed as planned?",
      [('pass', 'A contingency is explained (what happens if unavailable, delayed or declined).'),
       ('fail', 'No contingency is mentioned although the outcome is uncertain.'),
       ('NA', 'The outcome is certain on the call.')]),
    q('gen-48-customer-question-invited-mid', "general_qa",
      'Did the agent pause to invite questions during the explanation, not only at the end?',
      [('pass', 'The agent checks for questions at least once mid-explanation.'),
       ('fail', 'Questions are invited only at the end, or not at all.'),
       ('NA', 'No explanation long enough to warrant it is given.')]),
    q('gen-49-hold-or-wait-explained', "general_qa",
      'Where the customer had to wait while the agent looked something up, did the agent say what they were doing?',
      [('pass', "The agent narrates the wait ('bear with me while I check your booking')."),
       ('fail', 'There is silence or an unexplained pause.'),
       ('NA', 'No lookup or wait occurs.')]),
    q('gen-50-spelling-confirmed', "general_qa",
      'Where a name or address was given, was its spelling confirmed?',
      [('pass', 'The agent asks for or repeats the spelling of at least one name or address element.'),
       ('fail', 'Names or addresses are taken without confirming spelling.'),
       ('NA', 'No name or address is given.')]),
    q('spk-01-speakers-introduced', "general_qa",
      'Were the speakers introduced, by name or by who they are, at some point in the conversation?',
      [('pass', 'Every main speaker is introduced by name or by who they are.'),
       ('partial_pass', 'Some speakers are introduced, others never are.'),
       ('fail', 'No speaker is introduced.')], datasets=ALL),
    q('spk-03-speaking-time-shared', "general_qa",
      'Was speaking time shared reasonably between the speakers rather than one speaker monopolising it?',
      [('pass', 'Each main speaker contributes substantially.'),
       ('partial_pass', 'One speaker dominates but others still make sustained contributions.'),
       ('fail', 'One speaker delivers a near-monologue while others barely speak.')], datasets=ALL),
    q('spk-04-no-interrupting', "general_qa",
      'Did the speakers let each other finish speaking?',
      [('pass', 'Speakers are not cut off.'),
       ('partial_pass', 'Occasional interruptions that are acknowledged or yielded.'),
       ('fail', 'Speakers repeatedly talk over one another.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-05-clarifying-question', "general_qa",
      'When something said was unclear or ambiguous, did another speaker ask for clarification?',
      [('pass', 'A clarifying question is asked and answered.'),
       ('fail', 'Unclear statements pass without clarification.'),
       ('NA', 'Nothing said needed clarifying.')], datasets=ALL),
    q('spk-06-jargon-explained', "general_qa",
      'When technical terms, acronyms or specialist references were used, were they explained?',
      [('pass', 'Each specialist term is explained for a general listener.'),
       ('partial_pass', 'Some terms are explained, others assumed.'),
       ('fail', 'Specialist terms are used without explanation.'),
       ('NA', 'No specialist terms are used.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-07-claims-supported', "general_qa",
      'Were factual claims backed by a source, evidence, data or a concrete example?',
      [('pass', 'The main factual claims are supported.'),
       ('partial_pass', 'Some claims are supported, others asserted bare.'),
       ('fail', 'Claims are asserted without any support.'),
       ('NA', 'No factual claims are made.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-08-figures-specific', "general_qa",
      'When figures or quantities were given, were they specific rather than vague?',
      [('pass', 'Figures are given with actual numbers, dates or amounts.'),
       ('partial_pass', "A mix of specific and vague ('a lot', 'recently')."),
       ('fail', 'Only vague quantities are given.'),
       ('NA', 'No figures or quantities arise.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-10-disclosure-acknowledged', "general_qa",
      'When a speaker shared something personal or difficult, did another speaker acknowledge it?',
      [('pass', 'The disclosure is acknowledged before the conversation moves on.'),
       ('fail', 'The disclosure is passed over without acknowledgement.'),
       ('NA', 'No personal or difficult disclosure is made.')], datasets=["aci_bench", "sporc"]),
    q('spk-11-advice-given', "general_qa",
      'Did a speaker give advice or a recommendation directed at the listener?',
      [('fail', 'A speaker tells listeners what they should do, buy, avoid or try.'),
       ('pass', 'No advice or recommendation is directed at listeners.')], datasets=["apptek", "sporc"]),
    q('spk-12-advice-caveated', "general_qa",
      'Where financial, medical or legal advice was given, was a caveat or disclaimer stated?',
      [('pass', 'A caveat is stated (seek professional advice, individual circumstances vary, not advice).'),
       ('fail', 'Such advice is given with no caveat.'),
       ('NA', 'No financial, medical or legal advice is given.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-13-promotion-present', "general_qa",
      "Did the conversation include promotion of a product, service, sponsor or the speakers' own work?",
      [('fail', "A product, service, sponsor or the speakers' own offering is promoted."),
       ('pass', 'Nothing is promoted.')], datasets=["apptek", "sporc"]),
    q('spk-14-promotion-disclosed', "general_qa",
      'Where a product or service was promoted, was the commercial relationship (sponsorship, ownership, affiliation) made clear?',
      [('pass', 'The relationship is stated.'),
       ('fail', 'Promotion occurs with no disclosure of the relationship.'),
       ('NA', 'Nothing is promoted.')], datasets=["apptek", "sporc"]),
    q('spk-15-summary-at-end', "general_qa",
      'Was there a summary, conclusion or takeaway at the end of the conversation?',
      [('pass', 'A speaker wraps up with a summary or takeaway.'),
       ('partial_pass', 'A brief sign-off gestures at a conclusion without summarising.'),
       ('fail', 'The conversation ends without any wrap-up.')], datasets=ALL),
    q('spk-16-call-to-action', "general_qa",
      'Did a speaker ask listeners to do something (subscribe, visit, sign up, get in touch)?',
      [('fail', 'An explicit request to listeners is made.'),
       ('pass', 'No request is made of listeners.')], datasets=["apptek", "sporc"]),
    q('spk-17-questions-answered', "general_qa",
      'Were the questions one speaker put to another actually answered?',
      [('pass', 'Questions receive direct answers.'),
       ('partial_pass', 'Most are answered; some are deflected or left hanging.'),
       ('fail', 'Questions are largely evaded or ignored.'),
       ('NA', 'No speaker asks another a question.')], datasets=ALL),
    q('spk-18-topic-shifts-signposted', "general_qa",
      'Were changes of topic signposted rather than abrupt?',
      [('pass', 'Transitions are announced or bridged.'),
       ('partial_pass', 'Some transitions are signposted, others abrupt.'),
       ('fail', 'Topics change abruptly throughout.'),
       ('NA', 'The conversation stays on one topic.')], datasets=["apptek", "aci_bench", "sporc"]),
    q('spk-20-sensitive-topic-care', "general_qa",
      'Where a sensitive topic arose (illness, death, money troubles, abuse, addiction), was it handled with care?',
      [('pass', 'The topic is approached with sensitivity and without trivialising.'),
       ('fail', 'The topic is treated flippantly, judgementally or carelessly.'),
       ('NA', 'No sensitive topic arises.')], datasets=["aci_bench", "sporc"]),
    q('spk-21-listener-addressed', "general_qa",
      'Did a speaker address the listener directly at any point?',
      [('fail', "The audience is addressed directly ('you listening', 'if you are…')."),
       ('pass', 'The speakers only address each other.')], datasets=["sporc"]),
    q('spk-22-expertise-established', "general_qa",
      "Was the basis of a speaker's expertise or experience on the topic stated?",
      [('pass', "A speaker's relevant background or experience is stated."),
       ('partial_pass', 'Expertise is implied but never stated.'),
       ('fail', "No basis for any speaker's authority is given.")], datasets=["sporc"]),
    q('spk-23-offensive-language', "general_qa",
      'Did the conversation contain profanity or offensive language?',
      [('fail', 'Profanity or offensive language occurs.'),
       ('pass', 'None occurs.')], datasets=ALL),
    q('spk-24-claim-challenged', "general_qa",
      'When a surprising or contestable claim was made, did another speaker probe or challenge it?',
      [('pass', 'The claim is questioned or tested before being accepted.'),
       ('fail', 'Contestable claims pass unchallenged.'),
       ('NA', 'No contestable claim is made.')], datasets=["sporc"]),
    # ---- SPoRC, role-agnostic rare-event question (the customer-worded family questions do not apply to podcasts)
    q('spk-26-vulnerability-disclosed', "vulnerability",
      'Does any speaker disclose a characteristic of vulnerability about themselves?',
      [('fail', 'A speaker discloses, about themselves, a health condition, a significant life event, low financial resilience or low capability of the kinds described.'),
       ('pass', 'No speaker discloses such a characteristic about themselves; talking about other people or the topic in general does not count.')],
      description=VUL_DESC.replace("the customer", "the speaker").replace("customer's", "speaker's"), tags=FCA_TAGS, datasets=["sporc"]),
    # ---- ACI-Bench clinical visits (doctor / patient / patient_guest): the conduct the audit found meaningful there,
    # written for the clinic rather than substituted from the service-call wording
    q('aci-cmp-01-complaint', "complaint",
      'Does the patient make a complaint about their care or the service during the visit?',
      [('fail', 'The patient clearly states a problem with their care, treatment, the clinic or a previous encounter and asks for, or clearly expects, it to be put right.'),
       ('pass', 'No complaint is made. The patient may express frustration about symptoms or waiting, but does not state a problem with the care or service and seek a resolution.')],
      description=("A complaint is an expression of a problem with the care or service, together with a request or expectation that it be "
                   "resolved. Describing symptoms or discomfort is not a complaint."), datasets=["aci_bench"]),
    q('aci-eod-01-dissatisfaction', "eod",
      'Does the patient express dissatisfaction with their care, treatment or the service during the visit?',
      [('fail', 'The patient clearly expresses unhappiness or frustration with how they have been treated, a treatment that was given, the process or an outcome of care.'),
       ('pass', 'The patient is satisfied or neutral about their care; describing symptoms or worry about their health is not dissatisfaction with the care.')],
      description=("An expression of dissatisfaction is a clear statement of unhappiness with the care or service, whether or not the patient "
                   "asks for anything to be done. It is broader than a complaint."), datasets=["aci_bench"]),
    q('aci-03-identity-confirmed', "general_qa",
      "Was the patient's identity confirmed before their clinical details were discussed?",
      [('pass', 'The doctor confirms at least one identifying detail (full name, date of birth) before discussing records or results.'),
       ('partial_pass', 'Identity is confirmed only after clinical details have already been discussed.'),
       ('fail', 'No identity check takes place.'),
       ('NA', 'No records or results specific to the patient are discussed.')], datasets=["aci_bench"]),
    q('aci-11-risks-side-effects', "general_qa",
      'Were the risks, side effects or limitations of the treatment or option discussed made clear to the patient?',
      [('pass', 'The doctor states what could go wrong, what the side effects are, or what the treatment cannot do.'),
       ('partial_pass', 'Risks are alluded to but not explained.'),
       ('fail', 'Only the benefits of the treatment are described.'),
       ('NA', 'No treatment or option is discussed.')], datasets=["aci_bench"]),
    q('aci-12-plan-stated', "general_qa",
      'Were the key details of the plan (what will be done, when, for how long, and what follows) stated before the patient agreed to it?',
      [('pass', 'All key details of the plan are stated before the patient agrees.'),
       ('partial_pass', 'Most details are stated; at least one material element (dose, duration, follow-up) is missing.'),
       ('fail', 'The patient agrees to a plan whose details are not stated.'),
       ('NA', 'No plan is agreed.')], datasets=["aci_bench"]),
    q('aci-14-alternatives', "general_qa",
      'Were alternative treatments or options presented, or the reason for recommending one over others explained?',
      [('pass', 'At least one alternative is mentioned, or the choice is justified against alternatives.'),
       ('fail', 'A single course of action is presented as the only one with no justification.'),
       ('NA', 'No treatment or course of action is recommended.')], datasets=["aci_bench"]),
    q('aci-15-timescales', "general_qa",
      'Where something was to happen after the visit (results, referral, follow-up), was the patient given a specific timescale?',
      [('pass', 'A specific timescale (day, date or period) is given.'),
       ('partial_pass', "A vague timescale such as 'soon' or 'in a few weeks' is given."),
       ('fail', 'No timescale is given.'),
       ('NA', 'Nothing is to happen after the visit.')], datasets=["aci_bench"]),
    q('aci-16-history-read-back', "general_qa",
      'Were important details the patient provided (medications, doses, dates, symptom history) repeated back to confirm they were captured correctly?',
      [('pass', 'Details are repeated back and confirmed.'),
       ('fail', 'Important details are taken down without confirmation.'),
       ('NA', 'No such details are provided.')], datasets=["aci_bench"]),
    q('aci-18-empathy', "general_qa",
      'Where the patient expressed worry, frustration or distress, did the doctor acknowledge it?',
      [('pass', "The doctor acknowledges the patient's feeling before moving on."),
       ('fail', 'The feeling is ignored or dismissed.'),
       ('NA', 'The patient expresses no such feeling.')], datasets=["aci_bench"]),
    q('aci-19-name-use', "general_qa",
      "Did the doctor use the patient's name at least once after the opening?",
      [('pass', 'The patient is addressed by name during the visit, not only in the greeting.'),
       ('fail', "The patient's name is not used after the opening."),
       ('NA', "The patient's name is never established.")], datasets=["aci_bench"]),
    q('aci-20-questions-invited', "general_qa",
      'Was the patient given an opportunity to ask questions before the visit ended?',
      [('pass', 'The doctor explicitly asks whether the patient has any questions or concerns.'),
       ('fail', 'The visit is closed without any such invitation.')], datasets=["aci_bench"]),
    q('aci-21-next-steps', "general_qa",
      'Were the next steps summarised before the visit ended, including who does what and by when?',
      [('pass', 'What happens next, who is responsible and when are all stated.'),
       ('partial_pass', 'Next steps are mentioned without who or when.'),
       ('fail', 'No next steps are stated.'),
       ('NA', 'Nothing follows from the visit.')], datasets=["aci_bench"]),
    q('aci-23-consent', "general_qa",
      "Did the doctor obtain the patient's explicit agreement before ordering a test, starting or changing a medication, or making a referral?",
      [('pass', 'The doctor describes the test, medication or referral and the patient clearly agrees before it is arranged.'),
       ('fail', 'A test, medication or referral is arranged without clear agreement, or agreement is assumed.'),
       ('NA', 'No test, medication or referral is arranged.')], datasets=["aci_bench"]),
    q('aci-26-full-name', "general_qa",
      "Did the doctor establish or confirm the patient's full name?",
      [('pass', 'Both first name and surname are used or confirmed.'),
       ('partial_pass', 'Only a first name is used.'),
       ('fail', 'No name is used or confirmed.')], datasets=["aci_bench"]),
    q('aci-28-clarifying-question', "general_qa",
      "Where the patient's description of their problem was vague or incomplete, did the doctor ask clarifying questions before deciding?",
      [('pass', 'The doctor asks at least one clarifying question that narrows the problem.'),
       ('fail', 'The doctor proceeds on an assumption without clarifying.'),
       ('NA', "The patient's description is specific from the outset.")], datasets=["aci_bench"]),
    q('aci-34-appointment-quoted', "general_qa",
      'Where a follow-up, test or referral was arranged, was a specific date, time or interval quoted?',
      [('pass', 'A specific date, time or interval is quoted.'),
       ('partial_pass', 'Only an approximate window is quoted.'),
       ('fail', 'No date, time or interval is quoted.'),
       ('NA', 'Nothing is arranged for a future date.')], datasets=["aci_bench"]),
    q('aci-35-precautions-volunteered', "general_qa",
      'Did the doctor proactively mention a relevant precaution, restriction or warning sign that the patient had not asked about?',
      [('pass', 'At least one relevant precaution, restriction or warning sign is volunteered.'),
       ('fail', 'Precautions are only stated when the patient asks, or not at all.'),
       ('NA', 'No precautions apply to what is discussed.')], datasets=["aci_bench"]),
    q('aci-37-correction', "general_qa",
      'Did the patient have to correct the doctor about a detail of their history or situation during the visit?',
      [('pass', "The patient corrects no detail; the doctor's details are right first time."),
       ('partial_pass', 'The patient corrects one detail and the doctor accepts it.'),
       ('fail', 'The patient corrects the doctor more than once, or a correction is resisted.')], datasets=["aci_bench"]),
    q('aci-39-plan-recap', "general_qa",
      'Did the doctor recap the plan (diagnosis or working diagnosis, treatment, tests, follow-up) before ending the visit?',
      [('pass', 'The doctor restates the plan and the patient confirms.'),
       ('partial_pass', 'A partial recap that omits at least one element of the plan.'),
       ('fail', 'No recap is given.'),
       ('NA', 'No plan is made.')], datasets=["aci_bench"]),
    q('aci-40-further-help', "general_qa",
      "Did the doctor offer relevant additional help beyond the presenting problem (a screening, a referral, advice on a second concern)?",
      [('pass', 'A relevant further piece of help is offered.'),
       ('fail', 'Only the presenting problem is handled.'),
       ('NA', 'The visit ends before such an offer would be reasonable.')], datasets=["aci_bench"]),
    q('aci-41-contact-route', "general_qa",
      'Was the patient told how to get back in touch, or when to seek urgent care, if things changed?',
      [('pass', 'A specific route (number, portal, when to go to emergency care) is given.'),
       ('fail', 'The patient is left without a route to follow up.'),
       ('NA', 'No follow-up could be needed.')], datasets=["aci_bench"]),
    q('aci-44-sensitive-questions-explained', "general_qa",
      'When asking about sensitive matters (alcohol, drugs, sexual health, mental health, home situation), did the doctor explain why they were asking?',
      [('pass', 'A reason is given for each sensitive question.'),
       ('partial_pass', 'A reason is given for some sensitive questions but not others.'),
       ('fail', 'Sensitive questions are asked with no reason.'),
       ('NA', 'No sensitive questions are asked.')], datasets=["aci_bench"]),
    q('aci-45-option-comparison', "general_qa",
      'Where more than one treatment or option was presented, were the differences between them explained?',
      [('pass', 'The doctor explains how the options differ in effectiveness, side effects, burden or suitability.'),
       ('partial_pass', 'Options are listed with little or no comparison.'),
       ('fail', 'The patient is left to work out the differences.'),
       ('NA', 'Only one option is presented.')], datasets=["aci_bench"]),
    q('aci-47-contingency', "general_qa",
      "Did the doctor set the patient's expectations about what would happen if the treatment did not work or a result came back abnormal?",
      [('pass', 'A contingency is explained (what happens if no improvement, if a result is abnormal, if side effects occur).'),
       ('fail', 'No contingency is mentioned although the outcome is uncertain.'),
       ('NA', 'The outcome is certain at the visit.')], datasets=["aci_bench"]),
    q('aci-49-review-narrated', "general_qa",
      'Where the doctor paused to review records, results or images, did they say what they were doing?',
      [('pass', "The doctor narrates the pause ('let me have a look at your x-ray')."),
       ('fail', 'There is an unexplained pause or silence.'),
       ('NA', 'No such review occurs.')], datasets=["aci_bench"]),
    # ---- host behaviour (SPoRC only; the host is identified by identify_speakers.py and rendered `host:`)
    q('hst-01-sponsor-read', "general_qa",
      'Did the host read a sponsor message or advertisement during the episode?',
      [('fail', 'The host reads a sponsor message, advertisement or promotional code, however brief.'),
       ('pass', 'No sponsor message or advertisement is read by the host; mentions of products by other speakers do not count.')],
      description=("Only the host counts: this tests whether the host's turns can be told apart from everyone else's. A sponsor "
                   "message is an announcement on behalf of a third party (a company, product, service or offer), typically "
                   "with a name, offer or code, whether at the start, mid-episode or at the end."), datasets=["sporc"]),
    q('hst-02-host-named', "general_qa",
      'Did the host state their own name during the episode?',
      [('pass', 'The host says their own name (in an introduction, sign-off or aside).'),
       ('fail', 'The host never says their own name.')], datasets=["sporc"]),
    q('hst-03-guest-introduced', "general_qa",
      'Did the host introduce the guest(s) by name and say who they are or why they are on the show?',
      [('pass', 'Each guest is introduced by name with a description of who they are.'),
       ('partial_pass', 'A guest is named but not described, or described but not named.'),
       ('fail', 'A guest speaks without any introduction by the host.'),
       ('NA', 'There is no guest: the other speakers are co-hosts or the episode is a monologue with interjections.')],
      datasets=["sporc"]),
    q('hst-04-host-shares-floor', "general_qa",
      'Did the host give the other speakers room to answer, or dominate the conversation?',
      [('pass', 'The host asks and then listens; other speakers complete their answers.'),
       ('partial_pass', 'The host occasionally talks at length over what should be an answer, but others still get substantial turns.'),
       ('fail', "The host delivers long monologues, cuts answers short or answers their own questions.")], datasets=["sporc"]),
    q('hst-06-host-restates', "general_qa",
      "Did the host restate or summarise a point another speaker made, to check or highlight it?",
      [('pass', 'At least once the host paraphrases or summarises what another speaker said.'),
       ('fail', 'The host never restates or summarises anyone else\'s point.'),
       ('NA', 'No other speaker makes a substantive point.')], datasets=["sporc"]),
    q('hst-08-host-self-promotion', "general_qa",
      "Did the host promote their own products, memberships, social accounts or other shows?",
      [('fail', "The host promotes something of their own: a book, course, membership, newsletter, social account or another show."),
       ('pass', 'The host promotes nothing of their own; third-party sponsor messages do not count here.')], datasets=["sporc"]),
    q('hst-09-listener-messages', "general_qa",
      'Did the host read out or respond to listener messages, questions or reviews?',
      [('fail', 'The host reads or answers at least one message, question or review from a listener.'),
       ('pass', 'No listener messages, questions or reviews are read or answered.')], datasets=["sporc"]),
]

assert len({x.id for x in QUESTIONS}) == len(QUESTIONS), "duplicate question ids"


def all_questions(labelled_path: Path = OUT_DIR / "labelled_data.jsonl") -> list[Question]:
    """The bank plus every distinct question embedded in the labelled data."""
    seen = {x.id for x in QUESTIONS}
    out = list(QUESTIONS)
    if labelled_path.exists():
        for line in labelled_path.open():
            qd = json.loads(line)["question"]
            if qd["id"] not in seen:
                seen.add(qd["id"])
                out.append(Question.model_validate(qd))
    return out

# Taskmaster counterparts: the family questions and the conduct questions the audit found meaningful there.
TM_FROM = ["vul-01-present", "vul-02-handled", "cmp-01-complaint", "eod-01-dissatisfaction"] + [
    f"gen-{n}" for n in ("04-address", "05-contact-details", "06-data-protection", "07-needs-established", "08-affordability",
                         "09-open-questions", "10-costs-explained", "12-key-terms", "13-cancellation-rights", "14-alternatives",
                         "15-timescales", "16-read-back", "17-customer-actions", "19-name-use", "20-questions-invited",
                         "21-next-steps", "23-explicit-consent", "25-confirmation-to-follow", "26-full-name",
                         "28-clarifying-question", "29-preference-honoured", "30-availability-checked", "31-decline-explained",
                         "32-total-amount", "33-payment-method", "34-date-time-quoted", "35-conditions-mentioned",
                         "37-mistake-corrected", "39-recap-of-agreement", "40-further-help-offered", "41-contact-route",
                         "45-option-comparison", "46-email-or-number-readback", "47-expectation-set",
                         "49-hold-or-wait-explained", "50-spelling-confirmed")]
_by_id = {x.id: x for x in QUESTIONS}
QUESTIONS += [tm_variant(_by_id[i]) for i in TM_FROM]


def write_questions(labelled_path: Path = OUT_DIR / "labelled_data.jsonl",
                    out_path: Path = OUT_DIR / "questions.jsonl") -> int:
    qs = all_questions(labelled_path)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    with out_path.open("w") as f:
        for x in qs:
            f.write(x.model_dump_json() + "\n")
    return len(qs)


if __name__ == "__main__":
    from collections import Counter
    n = write_questions()
    print(f"wrote {n} questions ({len(QUESTIONS)} bank) -> {OUT_DIR / 'questions.jsonl'}")
    print(Counter(x.family for x in QUESTIONS))
